/* FiguRise - English dictionary */
window.__I18N_MERGE__("en", {
  "nav.home": "Home",
  "nav.products": "Products",
  "nav.about": "About Us",
  "nav.insights": "Insights",
  "nav.contact": "Contact",
  "nav.quote": "Get a Quote",
  "topbar.hint": "China Figure Export Factory · Serving Global Buyers",

  "hero.badge": "Made in China · Delivered Worldwide",
  "hero.title": "Your Premium <em>Figure</em> Manufacturing Partner for Global Markets",
  "hero.sub": "From prototype sculpting and injection molding to certified mass production and global logistics — a one-stop OEM/ODM factory covering prize figures, articulated figures, blind boxes and statues. Trusted by importers and wholesalers in 40+ countries.",
  "hero.cta1": "Browse the Catalog",
  "hero.cta2": "Get a Quote Now",
  "hero.scroll": "Scroll down",
  "hero.statYears": "Years of Manufacturing",
  "hero.statPartners": "Global Partners",
  "hero.statCapacity": "Annual Capacity (units)",
  "hero.statOnTime": "On-Time Delivery",

  "marquee.label": "Markets We Deliver To",

  "sec.strengths": "Core Strengths",
  "sec.strengthsSub": "Why global buyers choose FiguRise",
  "s1.t": "Full OEM / ODM Capability",
  "s1.d": "Licensed IP manufacturing and original design development — from 2D art, 3D modeling and prototype sculpting to mass production, fully in control.",
  "s2.t": "International Certification",
  "s2.d": "ISO9001, BSCI, CE, EN71, ASTM F963 — full compliance for EU, US, Middle East and Southeast Asia market access.",
  "s3.t": "Rapid Sampling in 7-15 Days",
  "s3.d": "Senior sculptors plus 3D printing rapid verification. Samples iterate until confirmed, cutting communication cost.",
  "s4.t": "End-to-End Supply Chain",
  "s4.d": "In-house mold, injection, spray painting, pad printing, UV printing and packaging lines — seamless across every step.",
  "s5.t": "Global Logistics Solutions",
  "s5.d": "Sea LCL/FCL, air freight, overseas warehousing and consolidated shipping lanes, optimized by destination.",
  "s6.t": "Dedicated Advisory Service",
  "s6.d": "One-to-one sales manager plus regional team, 12-hour response, full support from sampling to after-sales.",

  "sec.products": "Product Center",
  "sec.productsSub": "Six categories · OEM/ODM customization & bulk sourcing supported",
  "products.viewAll": "View All Products",
  "products.more": "Learn More",
  "c1.n": "Prize Figures",
  "c1.d": "Cost-effective volume movers for e-commerce & conventions",
  "c2.n": "Articulated Figures",
  "c2.d": "18+ joints, built for play & display",
  "c3.n": "Blind Boxes",
  "c3.d": "Hidden-chase play, a social-commerce hit",
  "c4.n": "Chibi Figures",
  "c4.d": "Cute route, first choice for gifting",
  "c5.n": "Collector Statues",
  "c5.d": "Resin craftsmanship for high-ticket collectors",
  "c6.n": "Mini Capsules",
  "c6.d": "Low-cost traffic drivers, multi-channel",

  "sec.regions": "Global Markets",
  "sec.regionsSub": "Focused on three key buyer markets with local teams",
  "r1.name": "Southeast Asia",
  "r1.desc": "Blind box and chibi demand is booming, driven by social commerce and young fans.",
  "r2.name": "Middle East",
  "r2.desc": "High-ticket collectibles, with a rising gifting economy and convention culture.",
  "r3.name": "Latin America",
  "r3.desc": "Fast-growing e-commerce penetration, rising local IP and anime culture.",
  "r.tag": "Market Profile",
  "r.hot": "Hot Categories",
  "r.advice": "Sourcing Advice",

  "sec.process": "How We Work",
  "sec.processSub": "Five steps to start, transparent at every stage",
  "proc1.t": "Inquiry & Discussion",
  "proc1.d": "Send your needs or pick products. Sales manager responds within 12 hours with a proposal.",
  "proc2.t": "Sample Confirmation",
  "proc2.d": "Sampling in 7-15 days with multiple revisions until approval. Sample fee is refundable.",
  "proc3.t": "Order Production",
  "proc3.d": "Mass production in 30-45 days after contract. Weekly progress reports.",
  "proc4.t": "Quality Inspection",
  "proc4.d": "Double assurance of full inspection plus third-party sampling. Inspection report before shipment.",
  "proc5.t": "Global Shipping",
  "proc5.d": "Sea/air/overseas warehouse. Full customs documents and tracking provided.",

  "sec.factory": "Factory Strength",
  "sec.factorySub": "Digital factory · 2M+ units annual capacity · 100% inspected",
  "f1.t": "Precision Injection Workshop",
  "f1.d": "32 injection machines, 60-500T, tolerance ±0.05mm.",
  "f2.t": "Dust-free Painting & Pad Printing",
  "f2.d": "Constant-temperature paint line plus automatic pad/silk printing, strict color control.",
  "f3.t": "3D Print Rapid Prototyping",
  "f3.d": "SLA/DLP verification, cutting prototype iteration time by 60%.",
  "f4.t": "Hand-finishing Workshop",
  "f4.d": "Senior hand painters for fine details and weathering effects.",
  "f5.t": "Packaging & Assembly",
  "f5.d": "Integrated gift box, blister and display box design and production.",
  "f6.t": "QC Laboratory",
  "f6.d": "Drop, tensile, heavy metal and phthalate testing. 100% final inspection.",

  "sec.testi": "What Buyers Say",
  "sec.testiSub": "Reviews from buyers across three key markets",
  "t1.q": "FiguRise's sampling speed gave us a head start in Vietnam's blind box peak season, and the quality has been consistently solid.",
  "t1.n": "Nguyen Van Minh",
  "t1.r": "Vietnam · E-commerce wholesaler",
  "t2.q": "They gave professional localization advice for the Saudi market and handled packaging and certification for us — saved us a lot of hassle.",
  "t2.n": "Ahmed Al-Rashid",
  "t2.r": "Saudi Arabia · Retail chain buyer",
  "t3.q": "From inquiry to first container in under 60 days, with complete Latin America customs documentation.",
  "t3.n": "Carlos Mendes",
  "t3.r": "Brazil · Importing wholesaler",

  "cta.title": "Ready to take Chinese figures to the world?",
  "cta.sub": "Send an inquiry for free product selection advice, quotes and sampling plans. Sales manager replies within 12 hours.",
  "cta.btn1": "Send Inquiry",
  "cta.btn2": "Ask the AI Brain",

  "footer.aboutText": "FiguRise has specialized in anime figures and trendy toys for 12 years. With end-to-end capability from prototype to mass production, we help global buyers enter the figure market more cost-effectively and reliably.",
  "footer.linksTitle": "Quick Links",
  "footer.catsTitle": "Categories",
  "footer.contactTitle": "Contact",
  "footer.regionsTitle": "Service Regions",
  "footer.rights": "All rights reserved.",
  "footer.privacy": "Privacy Policy",
  "footer.terms": "Terms of Service",

  "p.title": "Product Center",
  "p.sub": "Full-category figures · OEM/ODM customization and bulk sourcing · pricing on request",
  "p.all": "All Categories",
  "p.search": "Search products (name / keyword)…",
  "p.moq": "MOQ",
  "p.lead": "Lead Time",
  "p.scale": "Scale / Size",
  "p.inquire": "Inquire Now",
  "p.detail": "View Details",
  "p.close": "Close",
  "p.features": "Highlights",
  "p.why": "Why FiguRise",
  "p.empty": "No matching products. Try another keyword, or send an inquiry with your requirements.",
  "p.priceHint": "Price on request (customization & quantity discounts available)",
  "p.qty": "Estimated Quantity",
  "p.oem": "OEM/ODM supported",

  "a.title": "About Us",
  "a.sub": "A 12-year figure manufacturer from China's toy capital to the world",
  "a.storyTitle": "Our Story",
  "a.storyP1": "In 2014, we founded FiguRise in Shantou, the toy capital of China. What began as an 8-person sculptor studio has grown into a full-chain figure factory with twin bases in Shantou and Dongguan, 300+ employees and 2M+ units of annual capacity.",
  "a.storyP2": "We hold to our one-stop philosophy of 'from prototype to mass production': IP licensing compliance, original design, mold making, injection, painting, pad printing, packaging and logistics — all in-house, so our clients deal with just one window.",
  "a.storyP3": "Today FiguRise products reach 40+ countries across Southeast Asia, the Middle East, Latin America and Europe, serving e-commerce sellers, wholesalers, retail chains and trade-show buyers. We believe a great figure is not just a toy — it is culture and business.",
  "a.missionTitle": "Our Mission",
  "a.mission": "Help more Chinese figure brands go global more precisely and more reliably — matching China's supply chain efficiency with the aesthetics and compliance requirements of global markets.",
  "a.baseTitle": "Production Bases",
  "a.facTitle": "Core Facilities",
  "a.facSub": "In-house capacity covering every step of figure manufacturing",
  "a.qcTitle": "Quality System",
  "a.qcSub": "Four-layer QC gates to ensure defect-free containers",
  "q1.t": "IQC - Incoming",
  "q1.d": "100% sampling of raw materials, paint and packaging on arrival.",
  "q2.t": "IPQC - In Process",
  "q2.d": "Inspection records at injection, painting and assembly steps.",
  "q3.t": "FQC - Final",
  "q3.d": "100% check of appearance, function and assembly.",
  "q4.t": "OQC - Outgoing",
  "q4.d": "Third-party sampling plus full test reports with shipment.",
  "a.timelineTitle": "Milestones",
  "tl1.y": "2014",
  "tl1.t": "Founded in Shantou with an 8-person sculptor studio",
  "tl2.y": "2017",
  "tl2.t": "Full injection + painting lines completed, ISO9001 certified",
  "tl3.y": "2020",
  "tl3.t": "Dongguan base launched, capacity exceeds 1M units",
  "tl4.y": "2023",
  "tl4.t": "AI trade brain launched for smarter sourcing & marketing",
  "tl5.y": "2026",
  "tl5.t": "Serving 40+ countries, capacity reaches 2M units",
  "a.certTitle": "Certifications",
  "a.teamTitle": "Service Team",
  "a.teamSub": "We know products, markets and languages — one window to the world",
  "tms1.n": "Wang Min",
  "tms1.r": "Sales Manager, Southeast Asia",
  "tms2.n": "Ali Al-Rashid",
  "tms2.r": "Sales Manager, Middle East",
  "tms3.n": "Lucas Mendes",
  "tms3.r": "Sales Manager, Latin America",
  "tms4.n": "Chen Zhang",
  "tms4.r": "Project Engineer",

  "i.title": "Market Insights",
  "i.sub": "Figure market trends and sourcing guides for Southeast Asia, the Middle East and Latin America, updated by the FiguRise AI Brain",
  "i.region": "Market",
  "i.updated": "Updated",
  "i.readMore": "Read More",
  "i.points": "Key Points",
  "i.download": "Download Full Report",
  "i.note": "Content above is compiled from public data and first-line sourcing experience for product selection reference. Always verify with real-time market conditions and local regulations.",

  "c.title": "Contact Us",
  "c.sub": "Send an inquiry or reach the sales team directly — reply within 12 hours (GMT+8)",
  "c.formTitle": "Send Inquiry",
  "c.infoTitle": "Direct Contact",
  "c.whyTitle": "Why Choose Us",
  "c.name": "Name *",
  "c.company": "Company",
  "c.email": "Email *",
  "c.whatsapp": "WhatsApp / Phone",
  "c.country": "Country / Region",
  "c.category": "Product Category",
  "c.qty": "Estimated Quantity",
  "c.msg": "Requirements (style, IP, specs, target market…)",
  "c.phName": "Your name",
  "c.phCompany": "Company (optional)",
  "c.phEmail": "name@company.com",
  "c.phWhat": "+86 138 0000 0000",
  "c.phCountry": "e.g. Vietnam / Saudi / Mexico",
  "c.phQty": "e.g. First order 3,000 pcs",
  "c.phMsg": "Describe your product needs…",
  "c.submit": "Submit Inquiry",
  "c.successTitle": "Inquiry Received!",
  "c.successText": "Thank you! A sales manager will contact you within 12 hours (GMT+8) by email or WhatsApp. For urgent needs, add our WhatsApp directly.",
  "c.sendAnother": "Send Another Inquiry",
  "c.errName": "Please enter your name",
  "c.errEmail": "Please enter a valid email",
  "c.errMsg": "Please describe your needs briefly",
  "c.regionsTitle": "Regional Sales Managers",
  "c.officeLabel": "Coverage",
  "c.hours": "Working hours: Mon–Sat 9:00–18:00 (GMT+8)",
  "c.why1": "12 years of manufacturing, twin-base full production line",
  "c.why2": "Samples in 7-15 days, mass production in 30-45 days",
  "c.why3": "Fully certified + 100% inspected + complete customs documents",
  "c.why4": "Regional teams: SEA / Middle East / Latin America / Europe",
  "c.why5": "Free AI product selection & marketing advice",

  "bot.title": "FiguBot AI Trade Brain",
  "bot.status": "Online · Smart Reply",
  "bot.greeting": "Hi! I'm FiguBot, your figure export AI advisor. I can help you: <b>1. Product Selection Insights</b> · 2. Localized Content · 3. Smart Advertising · 4. Supply Chain Forecast.<br>Tap a feature card below or type your question.",
  "bot.placeholder": "Type your question…",
  "bot.quick1": "Product Selection",
  "bot.quick2": "Localized Content",
  "bot.quick3": "Smart Advertising",
  "bot.quick4": "Supply Chain",
  "bot.moduleTitle": "Choose a module",
  "bot.regionQ": "Select target market:",
  "bot.categoryQ": "Select category:",
  "bot.budgetQ": "Select monthly ad budget:",
  "bot.destQ": "Select destination country/region:",
  "bot.back": "Back",
  "bot.restart": "Restart",
  "bot.typing": "Thinking…",
  "bot.default": "I'm the AI Trade Brain. I offer four services: Product Selection Insights, Localized Content, Smart Advertising and Supply Chain Forecast. Tap a card below or ask directly (e.g. What is the MOQ?).",
  "bot.apiError": "Remote model connection failed. Switched to built-in knowledge engine.",
  "bot.copied": "Copied to clipboard",
  "bot.langs": "I answer in Chinese or English. For other languages, type in English.",
  "bot.gear": "Settings",
  "bot.cfgTitle": "Connect a Real LLM",
  "bot.cfgUrl": "API endpoint (OpenAI-compatible)",
  "bot.cfgKey": "API Key",
  "bot.cfgModel": "Model name",
  "bot.cfgMode": "Engine mode",
  "bot.cfgRemote": "Remote LLM",
  "bot.cfgLocal": "Built-in engine",
  "bot.cfgSave": "Save & Enable",
  "bot.cfgTest": "Test Connection",
  "bot.cfgReset": "Reset",
  "bot.cfgBack": "Back to Chat",
  "bot.cfgSaved": "Configuration saved!",
  "bot.cfgSavedTip": "Remote model enabled: free questions will call the LLM first; the four feature cards still use the built-in knowledge base (offline, instant).",
  "bot.cfgEmpty": "Reverted to the built-in knowledge engine — all questions answered locally.",
  "bot.cfgOk": "Connected, latency {ms} ms",
  "bot.cfgFail": "Connection failed: {msg}",
  "bot.cfgNeed": "Please fill in the API endpoint and API Key, or switch to the built-in engine.",
  "bot.cfgHint": "Your API Key is stored only in this browser's localStorage and never uploaded anywhere. For production, host a server-side proxy to hide the key.",
  "bot.engineLocal": "Built-in engine",
  "bot.engineRemote": "Remote model",

  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.next": "Next",
  "common.submit": "Submit",
  "common.copy": "Copy",
  "common.days": "days"
});
