/* FiguRise - 西班牙语 / 葡萄牙语 / 阿拉伯语 / 越南语 / 泰语 / 印尼语 词库 */
/* 说明：长文案（产品详情、洞察文章等）仅提供中/英，其余语种自动回退到英文 */

/* ================= 西班牙语 ================= */
window.__I18N_MERGE__("es", {
  "nav.home": "Inicio", "nav.products": "Productos", "nav.about": "Nosotros", "nav.insights": "Insights de Mercado", "nav.contact": "Contacto", "nav.quote": "Solicitar Cotización",
  "topbar.hint": "Fábrica china de figuras · Al servicio de compradores globales",
  "hero.badge": "Hecho en China · Entregado en todo el mundo",
  "hero.title": "Tu socio <em>figure</em> premium para mercados globales",
  "hero.sub": "Del esculturado de prototipos y el moldeo por inyección hasta la producción certificada y la logística global — una fábrica OEM/ODM integral de figuras de premio, articuladas, cajas sorpresa y estatuas. Con la confianza de importadores y mayoristas en más de 40 países.",
  "hero.cta1": "Ver Catálogo", "hero.cta2": "Cotizar Ahora", "hero.scroll": "Desplázate",
  "hero.statYears": "Años de fabricación", "hero.statPartners": "Socios globales", "hero.statCapacity": "Capacidad anual (uds.)", "hero.statOnTime": "Entregas a tiempo",
  "marquee.label": "Mercados donde entregamos",
  "sec.strengths": "Fortalezas Clave", "sec.strengthsSub": "Por qué los compradores globales eligen FiguRise",
  "s1.t": "Capacidad OEM / ODM completa", "s1.d": "Fabricación con IP licenciada y desarrollo de diseño original: del arte 2D, modelado 3D y escultura de prototipos a la producción en masa, todo bajo control.",
  "s2.t": "Certificación internacional", "s2.d": "ISO9001, BSCI, CE, EN71, ASTM F963: cumplimiento total para UE, EE. UU., Medio Oriente y Sudeste Asiático.",
  "s3.t": "Muestras rápidas en 7-15 días", "s3.d": "Escultores senior más verificación rápida con impresión 3D. Las muestras iteran hasta la aprobación, reduciendo costos.",
  "s4.t": "Cadena de suministro integral", "s4.d": "Moldes, inyección, pintura, tampografía, impresión UV y empaque propios: continuidad total en cada paso.",
  "s5.t": "Soluciones logísticas globales", "s5.d": "Marítimo LCL/FCL, aéreo, almacenes en el extranjero y rutas consolidadas, optimizados según destino.",
  "s6.t": "Servicio asesor dedicado", "s6.d": "Gerente de ventas 1 a 1 más equipo regional, respuesta en 12 horas, soporte completo desde muestras hasta postventa.",
  "sec.products": "Centro de Productos", "sec.productsSub": "Seis categorías · personalización OEM/ODM y compra al por mayor",
  "products.viewAll": "Ver Todos los Productos", "products.more": "Saber Más",
  "sec.regions": "Mercados Globales", "sec.regionsSub": "Enfocados en tres mercados clave con equipos locales",
  "r1.name": "Sudeste Asiático", "r1.desc": "La demanda de cajas sorpresa y figuras chibi está en auge, impulsada por el comercio social.",
  "r2.name": "Medio Oriente", "r2.desc": "Coleccionables de alto ticket, con economía de regalos y cultura de convenciones en crecimiento.",
  "r3.name": "América Latina", "r3.desc": "Penetración de e-commerce en rápido crecimiento, cultura anime e IP local en aumento.",
  "r.tag": "Perfil del mercado", "r.hot": "Categorías populares", "r.advice": "Consejos de compra",
  "sec.process": "Cómo Trabajamos", "sec.processSub": "Cinco pasos para comenzar, transparentes en cada etapa",
  "proc1.t": "Consulta y negociación", "proc1.d": "Envía tus necesidades o elige productos. El gerente de ventas responde en 12 horas con una propuesta.",
  "proc2.t": "Confirmación de muestra", "proc2.d": "Muestreo en 7-15 días con revisiones múltiples. La tarifa de muestra es reembolsable.",
  "proc3.t": "Producción del pedido", "proc3.d": "Producción en masa en 30-45 días tras el contrato, con informes de progreso semanales.",
  "proc4.t": "Inspección de calidad", "proc4.d": "Doble garantía: inspección completa más muestreo de terceros, con informe antes del envío.",
  "proc5.t": "Envío global", "proc5.d": "Marítimo/aéreo/almacén en el extranjero, con documentos aduaneros completos y seguimiento.",
  "sec.factory": "Fuerza de Fábrica", "sec.factorySub": "Fábrica digital · 2M+ unidades anuales · 100% inspeccionadas",
  "f1.t": "Taller de inyección de precisión", "f1.d": "32 máquinas de inyección, 60-500T, tolerancia ±0,05 mm.",
  "f2.t": "Pintura sin polvo y tampografía", "f2.d": "Línea de pintura a temperatura constante y impresión automática, con control estricto de color.",
  "f3.t": "Prototipado rápido 3D", "f3.d": "Verificación SLA/DLP, reduciendo el tiempo de iteración del prototipo un 60%.",
  "f4.t": "Taller de acabado manual", "f4.d": "Pintores senior para detalles finos y efectos de desgaste.",
  "f5.t": "Empaque y ensamblaje", "f5.d": "Diseño y producción integrados de cajas de regalo, blíster y cajas de exhibición.",
  "f6.t": "Laboratorio de control de calidad", "f6.d": "Pruebas de caída, tracción, metales pesados y ftalatos, con inspección final del 100%.",
  "sec.testi": "Qué Dicen los Compradores", "sec.testiSub": "Reseñas de compradores de tres mercados clave",
  "t1.q": "La velocidad de muestreo de FiguRise nos dio ventaja en la temporada alta de cajas sorpresa en Vietnam, con calidad siempre sólida.", "t1.n": "Nguyen Van Minh", "t1.r": "Vietnam · Mayorista de e-commerce",
  "t2.q": "Dieron consejos de localización profesionales para Arabia Saudita y manejaron empaque y certificación: nos ahorraron muchos problemas.", "t2.n": "Ahmed Al-Rashid", "t2.r": "Arabia Saudita · Comprador minorista",
  "t3.q": "De la consulta al primer contenedor en menos de 60 días, con documentación aduanera completa para América Latina.", "t3.n": "Carlos Mendes", "t3.r": "Brasil · Mayorista importador",
  "cta.title": "¿Listo para llevar figuras chinas al mundo?", "cta.sub": "Envía una consulta para recibir asesoría gratuita de selección, cotizaciones y planes de muestreo. Respuesta en 12 horas.",
  "cta.btn1": "Enviar Consulta", "cta.btn2": "Preguntar a la IA",
  "footer.aboutText": "FiguRise se especializa en figuras anime y juguetes de tendencia desde hace 12 años, ayudando a compradores globales a entrar al mercado de figuras de forma más rentable y confiable.",
  "footer.linksTitle": "Enlaces Rápidos", "footer.catsTitle": "Categorías", "footer.contactTitle": "Contacto", "footer.regionsTitle": "Regiones de Servicio",
  "footer.rights": "Todos los derechos reservados.", "footer.privacy": "Política de Privacidad", "footer.terms": "Términos del Servicio",
  "p.title": "Centro de Productos", "p.sub": "Figuras de todas las categorías · personalización OEM/ODM y compra al por mayor · precio bajo consulta",
  "p.all": "Todas las Categorías", "p.search": "Buscar productos (nombre / palabra clave)…", "p.moq": "MOQ", "p.lead": "Plazo de entrega", "p.scale": "Escala / Tamaño",
  "p.inquire": "Consultar Ahora", "p.detail": "Ver Detalles", "p.close": "Cerrar", "p.features": "Destacados", "p.why": "Por qué FiguRise",
  "p.empty": "Sin productos coincidentes. Prueba otra palabra clave o envía una consulta con tus requisitos.",
  "p.priceHint": "Precio bajo consulta (personalización y descuentos por volumen disponibles)", "p.qty": "Cantidad estimada", "p.oem": "OEM/ODM disponible",
  "a.title": "Sobre Nosotros", "a.sub": "Un fabricante de figuras con 12 años de experiencia, de la capital del juguete de China al mundo",
  "a.storyTitle": "Nuestra Historia",
  "a.storyP1": "En 2014 fundamos FiguRise en Shantou, la capital china del juguete. Lo que comenzó como un estudio de 8 escultores se ha convertido en una fábrica integral con bases gemelas en Shantou y Dongguan, más de 300 empleados y una capacidad anual de más de 2 millones de unidades.",
  "a.storyP2": "Mantenemos la filosofía integral 'del prototipo a la producción': licencias de IP, diseño original, moldes, inyección, pintura, tampografía, empaque y logística, todo interno, para que el cliente trate con una sola ventanilla.",
  "a.storyP3": "Hoy los productos FiguRise llegan a más de 40 países de Sudeste Asiático, Medio Oriente, América Latina y Europa, sirviendo a vendedores de e-commerce, mayoristas, cadenas minoristas y compradores de ferias.",
  "a.missionTitle": "Nuestra Misión", "a.mission": "Ayudar a más marcas chinas de figuras a globalizarse con mayor precisión y fiabilidad, uniendo la eficiencia de la cadena de suministro china con la estética y los requisitos de cumplimiento globales.",
  "a.baseTitle": "Bases de Producción", "a.facTitle": "Instalaciones Clave", "a.facSub": "Capacidad interna que cubre cada paso de la fabricación",
  "a.qcTitle": "Sistema de Calidad", "a.qcSub": "Cuatro niveles de control de calidad para contenedores sin defectos",
  "q1.t": "IQC - Entrada", "q1.d": "Muestreo del 100% de materias primas, pintura y empaque al llegar.",
  "q2.t": "IPQC - Proceso", "q2.d": "Registros de inspección en inyección, pintura y ensamblaje.",
  "q3.t": "FQC - Final", "q3.d": "Verificación del 100% de apariencia, función y ensamblaje.",
  "q4.t": "OQC - Salida", "q4.d": "Muestreo de terceros más informes de prueba completos con el envío.",
  "a.timelineTitle": "Hitos",
  "tl1.y": "2014", "tl1.t": "Fundada en Shantou con un estudio de 8 escultores",
  "tl2.y": "2017", "tl2.t": "Líneas completas de inyección y pintura, certificación ISO9001",
  "tl3.y": "2020", "tl3.t": "Lanzada la base de Dongguan, capacidad superior a 1M de unidades",
  "tl4.y": "2023", "tl4.t": "Cerebro comercial IA para selección y marketing inteligentes",
  "tl5.y": "2026", "tl5.t": "Sirviendo a más de 40 países, capacidad de 2M de unidades",
  "a.certTitle": "Certificaciones", "a.teamTitle": "Equipo de Servicio", "a.teamSub": "Conocemos productos, mercados e idiomas: una ventanilla al mundo",
  "i.title": "Informes de Mercado", "i.sub": "Tendencias del mercado de figuras y guías de compra para Sudeste Asiático, Medio Oriente y América Latina, actualizadas por el cerebro IA de FiguRise",
  "i.region": "Mercado", "i.updated": "Actualizado", "i.readMore": "Leer Más", "i.download": "Descargar Informe Completo",
  "i.note": "El contenido se elabora con datos públicos y experiencia de primera línea como referencia de selección. Verifica siempre con el mercado en tiempo real y las normativas locales.",
  "c.title": "Contáctanos", "c.sub": "Envía una consulta o contacta al equipo de ventas: respuesta en 12 horas (GMT+8)",
  "c.formTitle": "Enviar Consulta", "c.infoTitle": "Contacto Directo", "c.whyTitle": "Por Qué Elegirnos",
  "c.name": "Nombre *", "c.company": "Empresa", "c.email": "Correo *", "c.whatsapp": "WhatsApp / Teléfono", "c.country": "País / Región", "c.category": "Categoría", "c.qty": "Cantidad estimada",
  "c.msg": "Requisitos (estilo, IP, especificaciones, mercado objetivo…)",
  "c.phName": "Tu nombre", "c.phCompany": "Empresa (opcional)", "c.phEmail": "nombre@empresa.com", "c.phWhat": "+86 138 0000 0000", "c.phCountry": "ej. Vietnam / Arabia Saudita / México", "c.phQty": "ej. Primer pedido 3,000 pzas",
  "c.phMsg": "Describe tus necesidades de producto…", "c.submit": "Enviar Consulta",
  "c.successTitle": "¡Consulta Recibida!", "c.successText": "¡Gracias! Un gerente de ventas te contactará en 12 horas (GMT+8) por correo o WhatsApp. Para urgencias, agrega nuestro WhatsApp directamente.",
  "c.sendAnother": "Enviar Otra Consulta", "c.errName": "Ingresa tu nombre", "c.errEmail": "Ingresa un correo válido", "c.errMsg": "Describe brevemente tus necesidades",
  "c.regionsTitle": "Gerentes Regionales de Ventas", "c.officeLabel": "Cobertura", "c.hours": "Horario: Lun–Sáb 9:00–18:00 (GMT+8)",
  "c.why1": "12 años de fabricación, línea completa en dos bases", "c.why2": "Muestras en 7-15 días, producción en masa en 30-45 días",
  "c.why3": "Totalmente certificado + 100% inspeccionado + documentos completos", "c.why4": "Equipos regionales: SEA / Medio Oriente / América Latina / Europa", "c.why5": "Asesoría IA gratuita de selección y marketing",
  "bot.title": "FiguBot Cerebro Comercial IA", "bot.status": "En línea · Respuesta inteligente",
  "bot.greeting": "¡Hola! Soy FiguBot, tu asesor IA de exportación de figuras. Puedo ayudarte con: <b>1. Selección de Producto</b> · 2. Contenido Localizado · 3. Publicidad Inteligente · 4. Pronóstico de Cadena de Suministro.<br>Toca una tarjeta o escribe tu pregunta.",
  "bot.placeholder": "Escribe tu pregunta…", "bot.quick1": "Selección de Producto", "bot.quick2": "Contenido Localizado", "bot.quick3": "Publicidad Inteligente", "bot.quick4": "Cadena de Suministro",
  "bot.moduleTitle": "Elige un módulo", "bot.regionQ": "Selecciona el mercado objetivo:", "bot.categoryQ": "Selecciona la categoría:", "bot.budgetQ": "Selecciona el presupuesto mensual:", "bot.destQ": "Selecciona el país/región de destino:",
  "bot.back": "Volver", "bot.restart": "Reiniciar", "bot.typing": "Pensando…",
  "bot.default": "Soy el Cerebro Comercial IA. Ofrezco cuatro servicios: Selección de Producto, Contenido Localizado, Publicidad Inteligente y Pronóstico de Cadena de Suministro. Toca una tarjeta o pregunta directamente (ej. ¿Cuál es el MOQ?).",
  "bot.apiError": "Falló la conexión al modelo remoto. Cambiado al motor de conocimiento integrado.", "bot.copied": "Copiado al portapapeles", "bot.langs": "Respondo en chino o inglés. Para otros idiomas, escribe en inglés.",
  "common.close": "Cerrar", "common.cancel": "Cancelar", "common.next": "Siguiente", "common.submit": "Enviar", "common.copy": "Copiar", "common.days": "días"
});

/* ================= 葡萄牙语 ================= */
window.__I18N_MERGE__("pt", {
  "nav.home": "Início", "nav.products": "Produtos", "nav.about": "Sobre Nós", "nav.insights": "Insights de Mercado", "nav.contact": "Contato", "nav.quote": "Solicitar Orçamento",
  "topbar.hint": "Fábrica chinesa de figuras · Atendendo compradores globais",
  "hero.badge": "Feito na China · Entregue no mundo todo",
  "hero.title": "Seu parceiro <em>figure</em> premium para mercados globais",
  "hero.sub": "Da escultura de protótipos e injeção plástica à produção certificada e logística global — uma fábrica OEM/ODM completa de figures de prêmio, articuladas, blind boxes e estátuas. Confiada por importadores e atacadistas em mais de 40 países.",
  "hero.cta1": "Ver Catálogo", "hero.cta2": "Orçamento Agora", "hero.scroll": "Role para baixo",
  "hero.statYears": "Anos de fabricação", "hero.statPartners": "Parceiros globais", "hero.statCapacity": "Capacidade anual (un.)", "hero.statOnTime": "Entrega pontual",
  "marquee.label": "Mercados que atendemos",
  "sec.strengths": "Pontos Fortes", "sec.strengthsSub": "Por que compradores globais escolhem a FiguRise",
  "s1.t": "Capacidade total OEM / ODM", "s1.d": "Fabricação com IP licenciado e desenvolvimento de design original: da arte 2D, modelagem 3D e escultura de protótipos à produção em massa, tudo sob controle.",
  "s2.t": "Certificação internacional", "s2.d": "ISO9001, BSCI, CE, EN71, ASTM F963: conformidade total para UE, EUA, Oriente Médio e Sudeste Asiático.",
  "s3.t": "Amostras rápidas em 7-15 dias", "s3.d": "Escultores seniores com verificação rápida por impressão 3D. As amostras iteram até a aprovação, reduzindo custos.",
  "s4.t": "Cadeia de suprimentos completa", "s4.d": "Moldes, injeção, pintura, tampografia, impressão UV e embalagem próprios: continuidade total em cada etapa.",
  "s5.t": "Soluções logísticas globais", "s5.d": "Marítimo LCL/FCL, aéreo, armazéns no exterior e rotas consolidadas, otimizados por destino.",
  "s6.t": "Serviço consultivo dedicado", "s6.d": "Gerente de vendas 1 a 1 e equipe regional, resposta em 12 horas, suporte completo de amostras ao pós-venda.",
  "sec.products": "Centro de Produtos", "sec.productsSub": "Seis categorias · personalização OEM/ODM e compra em atacado",
  "products.viewAll": "Ver Todos os Produtos", "products.more": "Saiba Mais",
  "sec.regions": "Mercados Globais", "sec.regionsSub": "Foco em três mercados-chave com equipes locais",
  "r1.name": "Sudeste Asiático", "r1.desc": "A demanda por blind boxes e figures chibi está em alta, impulsionada pelo comércio social.",
  "r2.name": "Oriente Médio", "r2.desc": "Colecionáveis de alto valor, com economia de presentes e cultura de convenções em crescimento.",
  "r3.name": "América Latina", "r3.desc": "Penetração do e-commerce em rápido crescimento, cultura anime e IP local em alta.",
  "r.tag": "Perfil do mercado", "r.hot": "Categorias populares", "r.advice": "Dicas de compra",
  "sec.process": "Como Trabalhamos", "sec.processSub": "Cinco passos para começar, transparentes em cada etapa",
  "proc1.t": "Consulta e negociação", "proc1.d": "Envie suas necessidades ou escolha produtos. O gerente de vendas responde em 12 horas com uma proposta.",
  "proc2.t": "Confirmação de amostra", "proc2.d": "Amostragem em 7-15 dias com revisões múltiplas. A taxa de amostra é reembolsável.",
  "proc3.t": "Produção do pedido", "proc3.d": "Produção em massa em 30-45 dias após o contrato, com relatórios semanais de progresso.",
  "proc4.t": "Inspeção de qualidade", "proc4.d": "Garantia dupla: inspeção completa mais amostragem de terceiros, com relatório antes do envio.",
  "proc5.t": "Envio global", "proc5.d": "Marítimo/aéreo/armazém no exterior, com documentos aduaneiros completos e rastreamento.",
  "sec.factory": "Força da Fábrica", "sec.factorySub": "Fábrica digital · 2M+ unidades/ano · 100% inspecionadas",
  "f1.t": "Oficina de injeção de precisão", "f1.d": "32 máquinas de injeção, 60-500T, tolerância ±0,05 mm.",
  "f2.t": "Pintura sem poeira e tampografia", "f2.d": "Linha de pintura em temperatura constante e impressão automática, com controle rigoroso de cor.",
  "f3.t": "Prototipagem rápida 3D", "f3.d": "Verificação SLA/DLP, reduzindo o tempo de iteração do protótipo em 60%.",
  "f4.t": "Oficina de acabamento manual", "f4.d": "Pintores seniores para detalhes finos e efeitos de desgaste.",
  "f5.t": "Embalagem e montagem", "f5.d": "Design e produção integrados de caixas de presente, blister e caixas de exibição.",
  "f6.t": "Laboratório de controle de qualidade", "f6.d": "Testes de queda, tração, metais pesados e ftalatos, com inspeção final de 100%.",
  "sec.testi": "O Que os Compradores Dizem", "sec.testiSub": "Avaliações de compradores de três mercados-chave",
  "t1.q": "A velocidade de amostragem da FiguRise nos deu vantagem na alta temporada de blind boxes no Vietnã, com qualidade sempre sólida.", "t1.n": "Nguyen Van Minh", "t1.r": "Vietnã · Atacadista de e-commerce",
  "t2.q": "Deram conselhos profissionais de localização para a Arábia Saudita e cuidaram de embalagem e certificação: pouparam-nos muita dor de cabeça.", "t2.n": "Ahmed Al-Rashid", "t2.r": "Arábia Saudita · Comprador de varejo",
  "t3.q": "Da consulta ao primeiro contêiner em menos de 60 dias, com documentação aduaneira completa para a América Latina.", "t3.n": "Carlos Mendes", "t3.r": "Brasil · Atacadista importador",
  "cta.title": "Pronto para levar figures chinesas ao mundo?", "cta.sub": "Envie uma consulta para conselhos gratuitos de seleção, orçamentos e planos de amostragem. Resposta em 12 horas.",
  "cta.btn1": "Enviar Consulta", "cta.btn2": "Perguntar à IA",
  "footer.aboutText": "A FiguRise é especializada em figures anime e brinquedos da moda há 12 anos, ajudando compradores globais a entrar no mercado de figures de forma mais econômica e confiável.",
  "footer.linksTitle": "Links Rápidos", "footer.catsTitle": "Categorias", "footer.contactTitle": "Contato", "footer.regionsTitle": "Regiões Atendidas",
  "footer.rights": "Todos os direitos reservados.", "footer.privacy": "Política de Privacidade", "footer.terms": "Termos de Serviço",
  "p.title": "Centro de Produtos", "p.sub": "Figures de todas as categorias · personalização OEM/ODM e compra em atacado · preço sob consulta",
  "p.all": "Todas as Categorias", "p.search": "Buscar produtos (nome / palavra-chave)…", "p.moq": "MOQ", "p.lead": "Prazo de entrega", "p.scale": "Escala / Tamanho",
  "p.inquire": "Consultar Agora", "p.detail": "Ver Detalhes", "p.close": "Fechar", "p.features": "Destaques", "p.why": "Por que a FiguRise",
  "p.empty": "Nenhum produto encontrado. Tente outra palavra-chave ou envie uma consulta com seus requisitos.",
  "p.priceHint": "Preço sob consulta (personalização e descontos por volume disponíveis)", "p.qty": "Quantidade estimada", "p.oem": "OEM/ODM disponível",
  "a.title": "Sobre Nós", "a.sub": "Um fabricante de figures com 12 anos, da capital do brinquedo da China para o mundo",
  "a.storyTitle": "Nossa História",
  "a.storyP1": "Em 2014 fundamos a FiguRise em Shantou, a capital chinesa do brinquedo. O que começou como um estúdio de 8 escultores tornou-se uma fábrica completa com bases em Shantou e Dongguan, mais de 300 funcionários e capacidade anual superior a 2 milhões de unidades.",
  "a.storyP2": "Mantemos a filosofia 'do protótipo à produção': licenças de IP, design original, moldes, injeção, pintura, tampografia, embalagem e logística, tudo interno, para o cliente lidar com uma única janela.",
  "a.storyP3": "Hoje os produtos FiguRise chegam a mais de 40 países no Sudeste Asiático, Oriente Médio, América Latina e Europa, servindo vendedores de e-commerce, atacadistas, redes de varejo e compradores de feiras.",
  "a.missionTitle": "Nossa Missão", "a.mission": "Ajudar mais marcas chinesas de figures a se globalizar com mais precisão e confiabilidade, unindo a eficiência da cadeia de suprimentos chinesa à estética e conformidade dos mercados globais.",
  "a.baseTitle": "Bases de Produção", "a.facTitle": "Instalações Principais", "a.facSub": "Capacidade interna que cobre cada etapa da fabricação",
  "a.qcTitle": "Sistema de Qualidade", "a.qcSub": "Quatro níveis de controle de qualidade para contêineres sem defeitos",
  "q1.t": "IQC - Entrada", "q1.d": "Amostragem de 100% das matérias-primas, tinta e embalagem na chegada.",
  "q2.t": "IPQC - Processo", "q2.d": "Registros de inspeção em injeção, pintura e montagem.",
  "q3.t": "FQC - Final", "q3.d": "Verificação de 100% de aparência, função e montagem.",
  "q4.t": "OQC - Saída", "q4.d": "Amostragem de terceiros e relatórios de teste completos com o envio.",
  "a.timelineTitle": "Marcos",
  "tl1.y": "2014", "tl1.t": "Fundada em Shantou com um estúdio de 8 escultores",
  "tl2.y": "2017", "tl2.t": "Linhas completas de injeção e pintura, certificação ISO9001",
  "tl3.y": "2020", "tl3.t": "Base de Dongguan lançada, capacidade acima de 1M de unidades",
  "tl4.y": "2023", "tl4.t": "Cérebro comercial IA para seleção e marketing inteligentes",
  "tl5.y": "2026", "tl5.t": "Atendendo mais de 40 países, capacidade de 2M de unidades",
  "a.certTitle": "Certificações", "a.teamTitle": "Equipe de Serviço", "a.teamSub": "Conhecemos produtos, mercados e idiomas: uma janela para o mundo",
  "i.title": "Insights de Mercado", "i.sub": "Tendências do mercado de figures e guias de compra para Sudeste Asiático, Oriente Médio e América Latina, atualizados pelo cérebro IA da FiguRise",
  "i.region": "Mercado", "i.updated": "Atualizado", "i.readMore": "Ler Mais", "i.download": "Baixar Relatório Completo",
  "i.note": "O conteúdo é elaborado com dados públicos e experiência de primeira linha como referência de seleção. Sempre verifique o mercado em tempo real e as regulamentações locais.",
  "c.title": "Fale Conosco", "c.sub": "Envie uma consulta ou contate a equipe de vendas: resposta em 12 horas (GMT+8)",
  "c.formTitle": "Enviar Consulta", "c.infoTitle": "Contato Direto", "c.whyTitle": "Por Que Nos Escolher",
  "c.name": "Nome *", "c.company": "Empresa", "c.email": "E-mail *", "c.whatsapp": "WhatsApp / Telefone", "c.country": "País / Região", "c.category": "Categoria", "c.qty": "Quantidade estimada",
  "c.msg": "Requisitos (estilo, IP, especificações, mercado-alvo…)",
  "c.phName": "Seu nome", "c.phCompany": "Empresa (opcional)", "c.phEmail": "nome@empresa.com", "c.phWhat": "+86 138 0000 0000", "c.phCountry": "ex. Vietnã / Arábia Saudita / México", "c.phQty": "ex. Primeiro pedido 3.000 un.",
  "c.phMsg": "Descreva suas necessidades de produto…", "c.submit": "Enviar Consulta",
  "c.successTitle": "Consulta Recebida!", "c.successText": "Obrigado! Um gerente de vendas entrará em contato em 12 horas (GMT+8) por e-mail ou WhatsApp. Para urgências, adicione nosso WhatsApp diretamente.",
  "c.sendAnother": "Enviar Outra Consulta", "c.errName": "Digite seu nome", "c.errEmail": "Digite um e-mail válido", "c.errMsg": "Descreva brevemente suas necessidades",
  "c.regionsTitle": "Gerentes Regionais de Vendas", "c.officeLabel": "Cobertura", "c.hours": "Horário: Seg–Sáb 9:00–18:00 (GMT+8)",
  "c.why1": "12 anos de fabricação, linha completa em duas bases", "c.why2": "Amostras em 7-15 dias, produção em massa em 30-45 dias",
  "c.why3": "Totalmente certificado + 100% inspecionado + documentos completos", "c.why4": "Equipes regionais: SEA / Oriente Médio / América Latina / Europa", "c.why5": "Conselhos de IA gratuitos de seleção e marketing",
  "bot.title": "FiguBot Cérebro Comercial IA", "bot.status": "Online · Resposta inteligente",
  "bot.greeting": "Olá! Sou o FiguBot, seu consultor de IA de exportação de figures. Posso ajudar com: <b>1. Seleção de Produto</b> · 2. Conteúdo Localizado · 3. Publicidade Inteligente · 4. Previsão da Cadeia de Suprimentos.<br>Toque em um cartão ou digite sua pergunta.",
  "bot.placeholder": "Digite sua pergunta…", "bot.quick1": "Seleção de Produto", "bot.quick2": "Conteúdo Localizado", "bot.quick3": "Publicidade Inteligente", "bot.quick4": "Cadeia de Suprimentos",
  "bot.moduleTitle": "Escolha um módulo", "bot.regionQ": "Selecione o mercado-alvo:", "bot.categoryQ": "Selecione a categoria:", "bot.budgetQ": "Selecione o orçamento mensal:", "bot.destQ": "Selecione o país/região de destino:",
  "bot.back": "Voltar", "bot.restart": "Reiniciar", "bot.typing": "Pensando…",
  "bot.default": "Sou o Cérebro Comercial IA. Ofereço quatro serviços: Seleção de Produto, Conteúdo Localizado, Publicidade Inteligente e Previsão da Cadeia de Suprimentos. Toque em um cartão ou pergunte diretamente (ex. Qual é o MOQ?).",
  "bot.apiError": "Falha na conexão com o modelo remoto. Alternado para o mecanismo de conhecimento integrado.", "bot.copied": "Copiado para a área de transferência", "bot.langs": "Respondo em chinês ou inglês. Para outros idiomas, digite em inglês.",
  "common.close": "Fechar", "common.cancel": "Cancelar", "common.next": "Próximo", "common.submit": "Enviar", "common.copy": "Copiar", "common.days": "dias"
});

/* ================= 阿拉伯语 (RTL) ================= */
window.__I18N_MERGE__("ar", {
  "nav.home": "الرئيسية", "nav.products": "المنتجات", "nav.about": "من نحن", "nav.insights": "رؤى السوق", "nav.contact": "اتصل بنا", "nav.quote": "اطلب عرض سعر",
  "topbar.hint": "مصنع تماثيل صيني · نخدم المشترين حول العالم",
  "hero.badge": "صنع في الصين · شحن عالمي",
  "hero.title": "شريكك <em>المصنّع</em> للتماثيل الفاخرة في الأسواق العالمية",
  "hero.sub": "من نحت النماذج الأولية والحقن البلاستيكي إلى الإنتاج المعتمد والشحن العالمي — مصنع متكامل OEM/ODM للتماثيل الجوائز والمتحركة والصناديق الغامضة والتماثيل الكبيرة. موثوق من مستوردين وتجار جملة في أكثر من 40 دولة.",
  "hero.cta1": "تصفح الكتالوج", "hero.cta2": "اطلب عرض سعر الآن", "hero.scroll": "مرر للأسفل",
  "hero.statYears": "سنوات التصنيع", "hero.statPartners": "شركاء عالميون", "hero.statCapacity": "الطاقة السنوية (قطعة)", "hero.statOnTime": "التسليم في الموعد",
  "marquee.label": "الأسواق التي نخدمها",
  "sec.strengths": "نقاط القوة", "sec.strengthsSub": "لماذا يختار المشترون العالميون FiguRise",
  "s1.t": "قدرة OEM/ODM شاملة", "s1.d": "تصنيع بتراخيص IP وتطوير تصميمات أصلية — من الرسم ثنائي الأبعاد والنمذجة ثلاثية الأبعاد ونحت النماذج إلى الإنتاج الضخم، كل شيء تحت السيطرة.",
  "s2.t": "شهادات دولية", "s2.d": "ISO9001 وBSCI وCE وEN71 وASTM F963 — امتثال كامل لأسواق الاتحاد الأوروبي والولايات المتحدة والشرق الأوسط وجنوب شرق آسيا.",
  "s3.t": "عينات سريعة خلال 7-15 يومًا", "s3.d": "نحاتون محترفون مع تحقق سريع بالطباعة ثلاثية الأبعاد. تتكرر العينات حتى الاعتماد، مما يقلل تكاليف التواصل.",
  "s4.t": "سلسلة توريد متكاملة", "s4.d": "قوالب وحقن وطلاء وطباعة وسادة وطباعة UV وتغليف داخلية — استمرارية كاملة في كل خطوة.",
  "s5.t": "حلول لوجستية عالمية", "s5.d": "بحري LCL/FCL وجوي ومستودعات خارجية وخطوط شحن مجمعة، محسّنة حسب الوجهة.",
  "s6.t": "خدمة استشارية مخصصة", "s6.d": "مدير مبيعات فردي وفريق إقليمي، استجابة خلال 12 ساعة، ودعم كامل من العينات إلى ما بعد البيع.",
  "sec.products": "مركز المنتجات", "sec.productsSub": "ست فئات · دعم OEM/ODM والتوريد بالجملة",
  "products.viewAll": "عرض جميع المنتجات", "products.more": "اعرف المزيد",
  "sec.regions": "الأسواق العالمية", "sec.regionsSub": "تركيز على ثلاثة أسواق رئيسية مع فرق محلية",
  "r1.name": "جنوب شرق آسيا", "r1.desc": "الطلب على الصناديق الغامضة وتماثيل chibi في ازدهار بفضل التجارة الاجتماعية.",
  "r2.name": "الشرق الأوسط", "r2.desc": "مقتنيات عالية القيمة مع اقتصاد هدايا وثقافة معارض متنامية.",
  "r3.name": "أمريكا اللاتينية", "r3.desc": "انتشار سريع للتجارة الإلكترونية وارتفاع ثقافة الأنمي.",
  "r.tag": "ملامح السوق", "r.hot": "الفئات الرائجة", "r.advice": "نصائح التوريد",
  "sec.process": "كيف نعمل", "sec.processSub": "خمس خطوات للبدء بشفافية كاملة",
  "proc1.t": "الاستفسار والنقاش", "proc1.d": "أرسل احتياجاتك أو اختر المنتجات. يرد مدير المبيعات خلال 12 ساعة بمقترح.",
  "proc2.t": "اعتماد العينة", "proc2.d": "أخذ عينات خلال 7-15 يومًا مع مراجعات متعددة. رسوم العينة قابلة للاسترداد.",
  "proc3.t": "إنتاج الطلب", "proc3.d": "إنتاج ضخم خلال 30-45 يومًا بعد التعاقد مع تقارير أسبوعية.",
  "proc4.t": "فحص الجودة", "proc4.d": "ضمان مزدوج: فحص كامل وعينة من طرف ثالث، مع تقرير قبل الشحن.",
  "proc5.t": "الشحن العالمي", "proc5.d": "بحري/جوي/مستودعات خارجية مع مستندات جمركية كاملة وتتبع.",
  "sec.factory": "قوة المصنع", "sec.factorySub": "مصنع رقمي · أكثر من 2 مليون وحدة سنويًا · فحص 100%",
  "f1.t": "ورشة الحقن الدقيقة", "f1.d": "32 ماكينة حقن من 60-500 طن بدقة ±0.05 مم.",
  "f2.t": "طلاء وطباعة بدون غبار", "f2.d": "خط طلاء بدرجة حرارة ثابتة وطباعة أوتوماتيكية بضبط ألوان صارم.",
  "f3.t": "نماذج أولية سريعة ثلاثية الأبعاد", "f3.d": "تحقق SLA/DLP يقلص زمن التكرار 60%.",
  "f4.t": "ورشة التشطيب اليدوي", "f4.d": "رسامون محترفون للتفاصيل الدقيقة وتأثيرات التشطيب.",
  "f5.t": "التغليف والتجميع", "f5.d": "تصميم وإنتاج متكامل لعلب الهدايا والعلب الشفافة وعلب العرض.",
  "f6.t": "مختبر الجودة", "f6.d": "اختبارات السقوط والشد والمعادن الثقيلة والفثالات مع فحص نهائي 100%.",
  "sec.testi": "آراء المشترين", "sec.testiSub": "تقييمات من مشترين في ثلاثة أسواق رئيسية",
  "t1.q": "سرعة أخذ العينات في FiguRise منحتنا الأسبقية في موسم الذروة للصناديق الغامضة في فيتنام، والجودة ثابتة دائمًا.", "t1.n": "نغوين فان مينه", "t1.r": "فيتنام · تاجر جملة إلكتروني",
  "t2.q": "قدموا نصائح توطين احترافية للسوق السعودي وتعاملوا مع التغليف والشهادات — وفروا علينا الكثير.", "t2.n": "أحمد الراشد", "t2.r": "السعودية · مشترٍ لسلاسل التجزئة",
  "t3.q": "من الاستفسار إلى أول حاوية في أقل من 60 يومًا مع مستندات جمركية كاملة لأمريكا اللاتينية.", "t3.n": "كارلوس مينديز", "t3.r": "البرازيل · تاجر جملة مستورد",
  "cta.title": "هل أنت مستعد لإيصال التماثيل الصينية إلى العالم؟", "cta.sub": "أرسل استفسارًا للحصول على نصائح اختيار مجانية وعروض أسعار وخطط عينات. رد خلال 12 ساعة.",
  "cta.btn1": "إرسال استفسار", "cta.btn2": "اسأل العقل الذكي",
  "footer.aboutText": "تختص FiguRise في تماثيل الأنمي وألعاب الموضة منذ 12 عامًا. بقدرة متكاملة من النموذج الأولي إلى الإنتاج، نساعد المشترين العالميين على دخول سوق التماثيل بتكلفة أفضل وموثوقية أعلى.",
  "footer.linksTitle": "روابط سريعة", "footer.catsTitle": "الفئات", "footer.contactTitle": "تواصل معنا", "footer.regionsTitle": "مناطق الخدمة",
  "footer.rights": "جميع الحقوق محفوظة.", "footer.privacy": "سياسة الخصوصية", "footer.terms": "شروط الخدمة",
  "p.title": "مركز المنتجات", "p.sub": "تماثيل بجميع الفئات · OEM/ODM وتوريد بالجملة · السعر عند الطلب",
  "p.all": "جميع الفئات", "p.search": "ابحث عن منتجات (اسم / كلمة)…", "p.moq": "MOQ", "p.lead": "مدة التسليم", "p.scale": "المقياس/الحجم",
  "p.inquire": "استفسر الآن", "p.detail": "عرض التفاصيل", "p.close": "إغلاق", "p.features": "أبرز المزايا", "p.why": "لماذا FiguRise",
  "p.empty": "لا توجد منتجات مطابقة. جرّب كلمة أخرى أو أرسل استفسارًا باحتياجاتك.",
  "p.priceHint": "السعر عند الطلب (التخصيص وخصومات الكمية متاحة)", "p.qty": "الكمية التقديرية", "p.oem": "OEM/ODM متاح",
  "a.title": "من نحن", "a.sub": "مصنع تماثيل بخبرة 12 عامًا من عاصمة الألعاب الصينية إلى العالم",
  "a.storyTitle": "قصتنا",
  "a.storyP1": "في 2014 أسسنا FiguRise في شانتو، عاصمة الألعاب الصينية. ما بدأ كاستوديو من 8 نحاتين أصبح مصنعًا متكاملًا بقاعدتين في شانتو ودونغقوان وأكثر من 300 موظف وطاقة سنوية تتجاوز مليوني وحدة.",
  "a.storyP2": "نلتزم بفلسفة 'من النموذج الأولي إلى الإنتاج': تراخيص IP، التصميم الأصلي، القوالب، الحقن، الطلاء، الطباعة، التغليف واللوجستيات — كلها داخلية ليتعامل العميل مع نافذة واحدة.",
  "a.storyP3": "اليوم تصل منتجاتنا إلى أكثر من 40 دولة في جنوب شرق آسيا والشرق الأوسط وأمريكا اللاتينية وأوروبا، خدمة للبائعين الإلكترونيين وتجار الجملة وسلاسل التجزئة ومشتري المعارض.",
  "a.missionTitle": "مهمتنا", "a.mission": "مساعدة المزيد من العلامات الصينية على الوصول للعالم بدقة وثبات — بجمع كفاءة سلسلة التوريد الصينية مع متطلبات الجمال والامتثال للأسواق العالمية.",
  "a.baseTitle": "قواعد الإنتاج", "a.facTitle": "المنشآت الأساسية", "a.facSub": "قدرة داخلية تغطي كل خطوة في تصنيع التماثيل",
  "a.qcTitle": "نظام الجودة", "a.qcSub": "أربع مراحل فحص لضمان حاويات خالية من العيوب",
  "q1.t": "IQC - الوارد", "q1.d": "عينة 100% من المواد الخام والطلاء والتغليف عند الوصول.",
  "q2.t": "IPQC - أثناء الإنتاج", "q2.d": "سجلات فحص في الحقن والطلاء والتجميع.",
  "q3.t": "FQC - النهائي", "q3.d": "فحص 100% للمظهر والوظيفة والتجميع.",
  "q4.t": "OQC - الصادر", "q4.d": "عينة من طرف ثالث وتقارير اختبار كاملة مع الشحنة.",
  "a.timelineTitle": "محطاتنا",
  "tl1.y": "2014", "tl1.t": "التأسيس في شانتو باستوديو من 8 نحاتين",
  "tl2.y": "2017", "tl2.t": "اكتمال خطوط الحقن والطلاء وشهادة ISO9001",
  "tl3.y": "2020", "tl3.t": "إطلاق قاعدة دونغقوان وتجاوز الطاقة مليون وحدة",
  "tl4.y": "2023", "tl4.t": "إطلاق العقل الذكي للذكاء الاصطناعي للاختيار والتسويق",
  "tl5.y": "2026", "tl5.t": "خدمة أكثر من 40 دولة وطاقة مليوني وحدة",
  "a.certTitle": "الشهادات", "a.teamTitle": "فريق الخدمة", "a.teamSub": "نعرف المنتجات والأسواق واللغات — نافذة واحدة للعالم",
  "i.title": "رؤى السوق", "i.sub": "اتجاهات سوق التماثيل وأدلة التوريد لجنوب شرق آسيا والشرق الأوسط وأمريكا اللاتينية، محدثة من العقل الذكي",
  "i.region": "السوق", "i.updated": "محدث", "i.readMore": "اقرأ المزيد", "i.download": "تحميل التقرير الكامل",
  "i.note": "المحتوى أعلاه من بيانات عامة وخبرة ميدانية للرجوع إليها في اختيار المنتجات. تحقق دائمًا من السوق واللوائح المحلية.",
  "c.title": "اتصل بنا", "c.sub": "أرسل استفسارًا أو تواصل مع فريق المبيعات — رد خلال 12 ساعة (GMT+8)",
  "c.formTitle": "إرسال استفسار", "c.infoTitle": "تواصل مباشر", "c.whyTitle": "لماذا تختارنا",
  "c.name": "الاسم *", "c.company": "الشركة", "c.email": "البريد الإلكتروني *", "c.whatsapp": "واتساب / الهاتف", "c.country": "الدولة/المنطقة", "c.category": "فئة المنتج", "c.qty": "الكمية التقديرية",
  "c.msg": "المتطلبات (النمط، IP، المواصفات، السوق المستهدف…)",
  "c.phName": "اسمك", "c.phCompany": "الشركة (اختياري)", "c.phEmail": "name@company.com", "c.phWhat": "+86 138 0000 0000", "c.phCountry": "مثال: فيتنام / السعودية / المكسيك", "c.phQty": "مثال: الطلب الأول 3000 قطعة",
  "c.phMsg": "صف احتياجاتك من المنتجات…", "c.submit": "إرسال الاستفسار",
  "c.successTitle": "تم استلام الاستفسار!", "c.successText": "شكرًا لك! سيتواصل معك مدير المبيعات خلال 12 ساعة (GMT+8) عبر البريد أو واتساب. للعاجل، أضف واتسابنا مباشرة.",
  "c.sendAnother": "إرسال استفسار آخر", "c.errName": "الرجاء إدخال الاسم", "c.errEmail": "الرجاء إدخال بريد صحيح", "c.errMsg": "الرجاء وصف احتياجاتك باختصار",
  "c.regionsTitle": "مديرو المبيعات الإقليميون", "c.officeLabel": "التغطية", "c.hours": "ساعات العمل: الاثنين–السبت 9:00–18:00 (GMT+8)",
  "c.why1": "12 عامًا من التصنيع وخط إنتاج كامل في قاعدتين", "c.why2": "عينات خلال 7-15 يومًا وإنتاج خلال 30-45 يومًا",
  "c.why3": "شهادات كاملة + فحص 100% + مستندات جمركية شاملة", "c.why4": "فرق إقليمية: جنوب شرق آسيا / الشرق الأوسط / أمريكا اللاتينية / أوروبا", "c.why5": "نصائح ذكاء اصطناعي مجانية للاختيار والتسويق",
  "bot.title": "فيجوبوت العقل التجاري الذكي", "bot.status": "متصل · رد ذكي",
  "bot.greeting": "مرحبًا! أنا فيجوبوت مستشارك لتصدير التماثيل. يمكنني مساعدتك في: <b>1. رؤى اختيار المنتجات</b> · 2. المحتوى المترجم · 3. الإعلان الذكي · 4. توقع سلسلة التوريد.<br>اضغط على بطاقة أدناه أو اكتب سؤالك.",
  "bot.placeholder": "اكتب سؤالك…", "bot.quick1": "اختيار المنتجات", "bot.quick2": "المحتوى المترجم", "bot.quick3": "الإعلان الذكي", "bot.quick4": "سلسلة التوريد",
  "bot.moduleTitle": "اختر وحدة", "bot.regionQ": "اختر السوق المستهدف:", "bot.categoryQ": "اختر الفئة:", "bot.budgetQ": "اختر الميزانية الشهرية:", "bot.destQ": "اختر البلد/المنطقة:",
  "bot.back": "رجوع", "bot.restart": "إعادة البدء", "bot.typing": "أفكر…",
  "bot.default": "أنا العقل التجاري الذكي. أقدم أربع خدمات: رؤى اختيار المنتجات، المحتوى المترجم، الإعلان الذكي وتوقع سلسلة التوريد. اضغط بطاقة أو اسأل مباشرة (مثال: ما هو الحد الأدنى للطلب؟).",
  "bot.apiError": "فشل الاتصال بالنموذج البعيد. تم التبديل لمحرك المعرفة المدمج.", "bot.copied": "تم النسخ", "bot.langs": "أجيب بالصينية أو الإنجليزية. للغات أخرى اكتب بالإنجليزية.",
  "common.close": "إغلاق", "common.cancel": "إلغاء", "common.next": "التالي", "common.submit": "إرسال", "common.copy": "نسخ", "common.days": "يوم"
});

/* ================= 越南语 ================= */
window.__I18N_MERGE__("vi", {
  "nav.home": "Trang chủ", "nav.products": "Sản phẩm", "nav.about": "Về chúng tôi", "nav.insights": "Thị trường", "nav.contact": "Liên hệ", "nav.quote": "Báo giá",
  "topbar.hint": "Nhà máy figure Trung Quốc · Phục vụ khách hàng toàn cầu",
  "hero.badge": "Made in China · Giao hàng toàn cầu",
  "hero.title": "Đối tác <em>figure</em> cao cấp cho thị trường toàn cầu",
  "hero.sub": "Từ tạo mẫu, ép nhựa đến sản xuất chứng nhận và logistics toàn cầu — nhà máy OEM/ODM trọn gói cho figure, mô hình khớp nối, hộp mù và tượng sưu tầm. Được tin cậy bởi nhà nhập khẩu tại hơn 40 quốc gia.",
  "hero.cta1": "Xem danh mục", "hero.cta2": "Nhận báo giá", "hero.scroll": "Cuộn xuống",
  "hero.statYears": "Năm kinh nghiệm", "hero.statPartners": "Đối tác toàn cầu", "hero.statCapacity": "Công suất năm (sp)", "hero.statOnTime": "Giao đúng hạn",
  "marquee.label": "Thị trường chúng tôi phục vụ",
  "sec.strengths": "Thế mạnh cốt lõi", "sec.strengthsSub": "Vì sao khách hàng toàn cầu chọn FiguRise",
  "s1.t": "Năng lực OEM/ODM toàn diện", "s1.d": "Sản xuất IP có giấy phép và thiết kế nguyên bản — từ 2D, 3D, tạo mẫu đến sản xuất hàng loạt, hoàn toàn kiểm soát.",
  "s2.t": "Chứng nhận quốc tế", "s2.d": "ISO9001, BSCI, CE, EN71, ASTM F963 — đạt chuẩn EU, Mỹ, Trung Đông và Đông Nam Á.",
  "s3.t": "Lấy mẫu nhanh 7-15 ngày", "s3.d": "Đội tạo mẫu chuyên nghiệp + in 3D, mẫu chỉnh sửa đến khi duyệt, giảm chi phí trao đổi.",
  "s4.t": "Chuỗi cung ứng trọn gói", "s4.d": "Khuôn, ép nhựa, phun sơn, in pad, in UV và đóng gói tự làm — liền mạch từng bước.",
  "s5.t": "Giải pháp logistics toàn cầu", "s5.d": "Đường biển LCL/FCL, hàng không, kho ngoài nước, tối ưu theo điểm đến.",
  "s6.t": "Dịch vụ tư vấn tận tâm", "s6.d": "Quản lý bán hàng 1-1, phản hồi trong 12 giờ, hỗ trợ từ mẫu đến hậu mãi.",
  "sec.products": "Trung tâm sản phẩm", "sec.productsSub": "Sáu danh mục · Hỗ trợ OEM/ODM và mua sỉ",
  "products.viewAll": "Xem tất cả sản phẩm", "products.more": "Tìm hiểu thêm",
  "sec.regions": "Thị trường toàn cầu", "sec.regionsSub": "Tập trung ba thị trường trọng điểm với đội ngũ bản địa",
  "r1.name": "Đông Nam Á", "r1.desc": "Nhu cầu hộp mù và figure chibi bùng nổ nhờ thương mại xã hội.",
  "r2.name": "Trung Đông", "r2.desc": "Sưu tầm giá trị cao, kinh tế quà tặng và văn hóa sự kiện phát triển.",
  "r3.name": "Châu Mỹ Latinh", "r3.desc": "Thương mại điện tử tăng nhanh, văn hóa anime và IP bản địa nóng dần.",
  "r.tag": "Đặc điểm thị trường", "r.hot": "Danh mục hot", "r.advice": "Lời khuyên nhập hàng",
  "sec.process": "Quy trình hợp tác", "sec.processSub": "Năm bước khởi đầu, minh bạch từng giai đoạn",
  "proc1.t": "Trao đổi yêu cầu", "proc1.d": "Gửi nhu cầu hoặc chọn sản phẩm, quản lý bán hàng phản hồi trong 12 giờ.",
  "proc2.t": "Xác nhận mẫu", "proc2.d": "Lấy mẫu 7-15 ngày, chỉnh sửa đến khi duyệt, phí mẫu hoàn lại.",
  "proc3.t": "Sản xuất đơn hàng", "proc3.d": "Sản xuất hàng loạt 30-45 ngày sau hợp đồng, báo cáo tiến độ hàng tuần.",
  "proc4.t": "Kiểm tra chất lượng", "proc4.d": "Kiểm tra toàn bộ + kiểm tra bên thứ ba, báo cáo trước khi giao.",
  "proc5.t": "Giao hàng toàn cầu", "proc5.d": "Biển/hàng không/kho ngoài nước, đầy đủ chứng từ hải quan.",
  "sec.factory": "Năng lực nhà máy", "sec.factorySub": "Nhà máy số · 2 triệu sp/năm · Kiểm tra 100%",
  "f1.t": "Xưởng ép nhựa chính xác", "f1.d": "32 máy ép 60-500T, sai số ±0.05mm.",
  "f2.t": "Xưởng phun sơn sạch", "f2.d": "Dây chuyền phun sơn nhiệt độ ổn định, kiểm soát màu nghiêm ngặt.",
  "f3.t": "Tạo mẫu nhanh in 3D", "f3.d": "SLA/DLP giảm 60% thời gian lặp mẫu.",
  "f4.t": "Xưởng hoàn thiện thủ công", "f4.d": "Họa sĩ tay nghề cao cho chi tiết tinh xảo.",
  "f5.t": "Đóng gói & lắp ráp", "f5.d": "Thiết kế sản xuất hộp quà, vỉ nhựa, hộp trưng bày.",
  "f6.t": "Phòng thí nghiệm QC", "f6.d": "Kiểm tra rơi, kéo, kim loại nặng, phthalate; kiểm tra cuối 100%.",
  "sec.testi": "Khách hàng nói gì", "sec.testiSub": "Đánh giá từ ba thị trường trọng điểm",
  "t1.q": "Tốc độ lấy mẫu của FiguRise giúp chúng tôi đón đầu mùa cao điểm hộp mù tại Việt Nam.", "t1.n": "Nguyễn Văn Minh", "t1.r": "Việt Nam · Nhà bán sỉ online",
  "t2.q": "Họ tư vấn bản địa hóa chuyên nghiệp cho thị trường Ả Rập và lo trọn đóng gói, chứng nhận.", "t2.n": "Ahmed Al-Rashid", "t2.r": "Ả Rập Saudi · Nhà mua chuỗi bán lẻ",
  "t3.q": "Từ hỏi báo giá đến container đầu tiên chưa đến 60 ngày, chứng từ hải quan đầy đủ.", "t3.n": "Carlos Mendes", "t3.r": "Brazil · Nhà nhập khẩu sỉ",
  "cta.title": "Sẵn sàng đưa figure Trung Quốc ra thế giới?", "cta.sub": "Gửi yêu cầu để nhận tư vấn chọn sản phẩm miễn phí, báo giá và kế hoạch lấy mẫu.",
  "cta.btn1": "Gửi yêu cầu", "cta.btn2": "Hỏi AI Brain",
  "footer.aboutText": "FiguRise chuyên sản xuất figure anime và đồ chơi xu hướng 12 năm, giúp nhà mua toàn cầu vào thị trường figure hiệu quả và bền vững.",
  "footer.linksTitle": "Liên kết nhanh", "footer.catsTitle": "Danh mục", "footer.contactTitle": "Liên hệ", "footer.regionsTitle": "Khu vực phục vụ",
  "footer.rights": "Bảo lưu mọi quyền.", "footer.privacy": "Chính sách bảo mật", "footer.terms": "Điều khoản dịch vụ",
  "p.title": "Trung tâm sản phẩm", "p.sub": "Figure đủ danh mục · OEM/ODM và mua sỉ · Giá theo yêu cầu",
  "p.all": "Tất cả danh mục", "p.search": "Tìm sản phẩm (tên / từ khóa)…", "p.moq": "MOQ", "p.lead": "Thời gian giao", "p.scale": "Tỉ lệ/Kích thước",
  "p.inquire": "Hỏi báo giá", "p.detail": "Xem chi tiết", "p.close": "Đóng", "p.features": "Điểm nổi bật", "p.why": "Vì sao chọn FiguRise",
  "p.empty": "Không tìm thấy sản phẩm. Thử từ khóa khác hoặc gửi yêu cầu của bạn.",
  "p.priceHint": "Giá theo yêu cầu (tùy chỉnh và chiết khấu số lượng)", "p.qty": "Số lượng dự kiến", "p.oem": "Hỗ trợ OEM/ODM",
  "a.title": "Về chúng tôi", "a.sub": "Nhà sản xuất figure 12 năm từ thủ đô đồ chơi Trung Quốc",
  "a.storyTitle": "Câu chuyện của chúng tôi",
  "a.storyP1": "Năm 2014, chúng tôi thành lập FiguRise tại Sán Đầu. Từ studio 8 nhà tạo mẫu, nay là nhà máy trọn chuỗi với hai cơ sở Sán Đầu và Đông Quản, hơn 300 nhân viên.",
  "a.storyP2": "Chúng tôi giữ triết lý 'từ mẫu đến sản xuất hàng loạt': IP hợp pháp, thiết kế gốc, khuôn, ép, sơn, in, đóng gói, logistics — tất cả nội bộ.",
  "a.storyP3": "Hôm nay sản phẩm FiguRise có mặt tại hơn 40 quốc gia phục vụ nhà bán online, nhà sỉ, chuỗi bán lẻ.",
  "a.missionTitle": "Sứ mệnh", "a.mission": "Giúp thương hiệu figure Trung Quốc vươn ra toàn cầu chính xác và bền vững hơn.",
  "a.baseTitle": "Cơ sở sản xuất", "a.facTitle": "Cơ sở chính", "a.facSub": "Năng lực nội bộ phủ mọi công đoạn",
  "a.qcTitle": "Hệ thống chất lượng", "a.qcSub": "Bốn tầng kiểm soát chất lượng",
  "q1.t": "IQC - Nhập hàng", "q1.d": "Kiểm tra mẫu 100% nguyên liệu, sơn, bao bì khi về.",
  "q2.t": "IPQC - Trong quy trình", "q2.d": "Ghi chép kiểm tra ép, sơn, lắp ráp.",
  "q3.t": "FQC - Thành phẩm", "q3.d": "Kiểm tra 100% ngoại quan, chức năng, lắp ráp.",
  "q4.t": "OQC - Xuất hàng", "q4.d": "Kiểm tra bên thứ ba + đầy đủ báo cáo.",
  "a.timelineTitle": "Cột mốc",
  "tl1.y": "2014", "tl1.t": "Thành lập tại Sán Đầu",
  "tl2.y": "2017", "tl2.t": "Hoàn thiện dây chuyền ép + sơn, đạt ISO9001",
  "tl3.y": "2020", "tl3.t": "Cơ sở Đông Quản, công suất vượt 1 triệu",
  "tl4.y": "2023", "tl4.t": "Ra mắt AI Brain cho chọn sản phẩm và marketing",
  "tl5.y": "2026", "tl5.t": "Phục vụ 40+ quốc gia, công suất 2 triệu",
  "a.certTitle": "Chứng nhận", "a.teamTitle": "Đội ngũ dịch vụ", "a.teamSub": "Hiểu sản phẩm, thị trường và ngôn ngữ",
  "i.title": "Thị trường", "i.sub": "Xu hướng thị trường figure và hướng dẫn nhập hàng Đông Nam Á, Trung Đông, Mỹ Latinh",
  "i.region": "Thị trường", "i.updated": "Cập nhật", "i.readMore": "Đọc thêm", "i.download": "Tải báo cáo đầy đủ",
  "i.note": "Nội dung từ dữ liệu công khai và kinh nghiệm nhập hàng để tham khảo; luôn xác minh với thị trường thực tế.",
  "c.title": "Liên hệ", "c.sub": "Gửi yêu cầu hoặc liên hệ đội bán hàng — phản hồi trong 12 giờ (GMT+8)",
  "c.formTitle": "Gửi yêu cầu", "c.infoTitle": "Liên hệ trực tiếp", "c.whyTitle": "Vì sao chọn chúng tôi",
  "c.name": "Tên *", "c.company": "Công ty", "c.email": "Email *", "c.whatsapp": "WhatsApp / Điện thoại", "c.country": "Quốc gia / Khu vực", "c.category": "Danh mục", "c.qty": "Số lượng dự kiến",
  "c.msg": "Yêu cầu (kiểu dáng, IP, thông số, thị trường…)",
  "c.phName": "Tên của bạn", "c.phCompany": "Công ty (tùy chọn)", "c.phEmail": "name@company.com", "c.phWhat": "+86 138 0000 0000", "c.phCountry": "VD: Việt Nam / Ả Rập / Mexico", "c.phQty": "VD: Đơn đầu 3.000 sp",
  "c.phMsg": "Mô tả nhu cầu sản phẩm…", "c.submit": "Gửi yêu cầu",
  "c.successTitle": "Đã nhận yêu cầu!", "c.successText": "Cảm ơn! Quản lý bán hàng sẽ liên hệ trong 12 giờ (GMT+8) qua email hoặc WhatsApp.",
  "c.sendAnother": "Gửi yêu cầu khác", "c.errName": "Vui lòng nhập tên", "c.errEmail": "Vui lòng nhập email hợp lệ", "c.errMsg": "Vui lòng mô tả nhu cầu",
  "c.regionsTitle": "Quản lý khu vực", "c.officeLabel": "Phụ trách", "c.hours": "Giờ làm việc: T2–T7 9:00–18:00 (GMT+8)",
  "c.why1": "12 năm sản xuất, hai cơ sở", "c.why2": "Mẫu 7-15 ngày, sản xuất 30-45 ngày",
  "c.why3": "Chứng nhận đầy đủ + kiểm tra 100% + chứng từ", "c.why4": "Đội ngũ khu vực: ĐNA / Trung Đông / Mỹ Latinh / Châu Âu", "c.why5": "Tư vấn AI miễn phí",
  "bot.title": "FiguBot AI Trade Brain", "bot.status": "Trực tuyến · Trả lời thông minh",
  "bot.greeting": "Xin chào! Tôi là FiguBot, cố vấn AI xuất khẩu figure. Tôi giúp bạn: <b>1. Chọn sản phẩm</b> · 2. Nội dung bản địa hóa · 3. Quảng cáo thông minh · 4. Dự báo chuỗi cung ứng.<br>Nhấn thẻ bên dưới hoặc nhập câu hỏi.",
  "bot.placeholder": "Nhập câu hỏi…", "bot.quick1": "Chọn sản phẩm", "bot.quick2": "Nội dung bản địa hóa", "bot.quick3": "Quảng cáo thông minh", "bot.quick4": "Chuỗi cung ứng",
  "bot.moduleTitle": "Chọn chức năng", "bot.regionQ": "Chọn thị trường mục tiêu:", "bot.categoryQ": "Chọn danh mục:", "bot.budgetQ": "Chọn ngân sách quảng cáo tháng:", "bot.destQ": "Chọn quốc gia/khu vực đích:",
  "bot.back": "Quay lại", "bot.restart": "Bắt đầu lại", "bot.typing": "Đang suy nghĩ…",
  "bot.default": "Tôi là AI Trade Brain. Tôi cung cấp bốn dịch vụ: Chọn sản phẩm, Nội dung bản địa hóa, Quảng cáo thông minh và Dự báo chuỗi cung ứng. Nhấn thẻ hoặc hỏi trực tiếp (VD: MOQ là bao nhiêu?).",
  "bot.apiError": "Kết nối mô hình từ xa thất bại. Đã chuyển sang công cụ kiến thức tích hợp.", "bot.copied": "Đã sao chép", "bot.langs": "Tôi trả lời bằng tiếng Trung hoặc Anh. Ngôn ngữ khác vui lòng nhập bằng tiếng Anh.",
  "common.close": "Đóng", "common.cancel": "Hủy", "common.next": "Tiếp theo", "common.submit": "Gửi", "common.copy": "Sao chép", "common.days": "ngày"
});

/* ================= 泰语 ================= */
window.__I18N_MERGE__("th", {
  "nav.home": "หน้าแรก", "nav.products": "สินค้า", "nav.about": "เกี่ยวกับเรา", "nav.insights": "ตลาด", "nav.contact": "ติดต่อเรา", "nav.quote": "ขอใบเสนอราคา",
  "topbar.hint": "โรงงานฟิกเกอร์จีน · บริการลูกค้าทั่วโลก",
  "hero.badge": "ผลิตในจีน · จัดส่งทั่วโลก",
  "hero.title": "พาร์ทเนอร์ผลิต<em>ฟิกเกอร์</em>คุณภาพสูงสำหรับตลาดโลก",
  "hero.sub": "ตั้งแต่การปั้นต้นแบบ ฉีดพลาสติก ไปจนถึงการผลิตที่ผ่านมาตรฐานและโลจิสติกส์ทั่วโลก — โรงงาน OEM/ODM ครบวงจรสำหรับฟิกเกอร์ Prize, Articulated, กล่องสุ่ม และสตาทิว ไว้วางใจโดยผู้นำเข้าในกว่า 40 ประเทศ",
  "hero.cta1": "ดูแคตตาล็อก", "hero.cta2": "ขอใบเสนอราคา", "hero.scroll": "เลื่อนลง",
  "hero.statYears": "ปีประสบการณ์ผลิต", "hero.statPartners": "พาร์ทเนอร์ทั่วโลก", "hero.statCapacity": "กำลังผลิตต่อปี (ชิ้น)", "hero.statOnTime": "จัดส่งตรงเวลา",
  "marquee.label": "ตลาดที่เราให้บริการ",
  "sec.strengths": "จุดแข็งหลัก", "sec.strengthsSub": "ทำไมลูกค้าทั่วโลกเลือก FiguRise",
  "s1.t": "ความสามารถ OEM/ODM ครบวงจร", "s1.d": "ผลิตสินค้า IP ที่ได้รับอนุญาตและพัฒนาดีไซน์ดั้งเดิม — ตั้งแต่ภาพ 2D, โมเดล 3D, การปั้นต้นแบบ ถึงการผลิตจำนวนมาก",
  "s2.t": "มาตรฐานรับรองระดับสากล", "s2.d": "ISO9001, BSCI, CE, EN71, ASTM F963 ผ่านมาตรฐาน EU, สหรัฐฯ, ตะวันออกกลาง และเอเชียตะวันออกเฉียงใต้",
  "s3.t": "ทำตัวอย่างรวดเร็ว 7-15 วัน", "s3.d": "ทีมช่างปั้นมืออาชีพ + พิมพ์ 3D ตรวจสอบเร็ว แก้จนกว่าจะอนุมัติ",
  "s4.t": "ห่วงโซ่อุปทานครบวงจร", "s4.d": "แม่พิมพ์ ฉีด พ่นสี พิมพ์แพด พิมพ์ UV และบรรจุภัณฑ์ในโรงงานเดียว",
  "s5.t": "โซลูชันโลจิสติกส์ทั่วโลก", "s5.d": "ทางเรือ LCL/FCL ทางอากาศ คลังต่างประเทศ ปรับตามจุดหมาย",
  "s6.t": "บริการที่ปรึกษาเฉพาะบุคคล", "s6.d": "ผู้จัดการขาย 1-1 ตอบภายใน 12 ชั่วโมง ดูแลตั้งแต่ตัวอย่างถึงหลังการขาย",
  "sec.products": "ศูนย์สินค้า", "sec.productsSub": "หกหมวด · รองรับ OEM/ODM และสั่งขายส่ง",
  "products.viewAll": "ดูสินค้าทั้งหมด", "products.more": "เรียนรู้เพิ่มเติม",
  "sec.regions": "ตลาดทั่วโลก", "sec.regionsSub": "เจาะสามตลาดหลักพร้อมทีมท้องถิ่น",
  "r1.name": "เอเชียตะวันออกเฉียงใต้", "r1.desc": "ความต้องการกล่องสุ่มและฟิกเกอร์ชิบิบูมจากโซเชียลคอมเมิร์ซ",
  "r2.name": "ตะวันออกกลาง", "r2.desc": "ของสะสมราคาสูง เศรษฐกิจของขวัญและวัฒนธรรมคอนเวนชันโตขึ้น",
  "r3.name": "ลาตินอเมริกา", "r3.desc": "อีคอมเมิร์ซโตเร็ว วัฒนธรรมอนิเมะและ IP ท้องถิ่นร้อนแรง",
  "r.tag": "ลักษณะตลาด", "r.hot": "หมวดหมู่ฮิต", "r.advice": "คำแนะนำการสั่งซื้อ",
  "sec.process": "กระบวนการร่วมงาน", "sec.processSub": "ห้าขั้นตอน โปร่งใสทุกช่วง",
  "proc1.t": "สอบถามและคุยรายละเอียด", "proc1.d": "ส่งความต้องการหรือเลือกสินค้า ผู้จัดการขายตอบภายใน 12 ชั่วโมง",
  "proc2.t": "ยืนยันตัวอย่าง", "proc2.d": "ทำตัวอย่าง 7-15 วัน แก้จนพอใจ ค่าตัวอย่างคืนได้",
  "proc3.t": "ผลิตตามออเดอร์", "proc3.d": "ผลิตจำนวนมาก 30-45 วันหลังเซ็นสัญญา รายงานความคืบหน้ารายสัปดาห์",
  "proc4.t": "ตรวจสอบคุณภาพ", "proc4.d": "ตรวจทั้งหมด + สุ่มตรวจโดยบุคคลที่สาม รายงานก่อนจัดส่ง",
  "proc5.t": "จัดส่งทั่วโลก", "proc5.d": "ทางเรือ/อากาศ/คลังต่างประเทศ เอกสารศุลกากรครบ",
  "sec.factory": "ความแข็งแกร่งของโรงงาน", "sec.factorySub": "โรงงานดิจิทัล · กำลังผลิต 2 ล้านชิ้น/ปี · ตรวจสอบ 100%",
  "f1.t": "โรงงานฉีดพลาสติกแม่นยำ", "f1.d": "เครื่องฉีด 32 เครื่อง 60-500T ความคลาดเคลื่อน ±0.05มม.",
  "f2.t": "โรงพ่นสีไร้ฝุ่น", "f2.d": "สายพ่นสีอุณหภูมิคงที่ ควบคุมสีเข้มงวด",
  "f3.t": "ต้นแบบพิมพ์ 3D เร็ว", "f3.d": "SLA/DLP ลดเวลาทำซ้ำต้นแบบ 60%",
  "f4.t": "โรงเก็บรายละเอียดมือ", "f4.d": "ช่างทาสีมือฝีมือดี รายละเอียดละเอียดลออ",
  "f5.t": "บรรจุภัณฑ์และประกอบ", "f5.d": "ออกแบบผลิตกล่องของขวัญ กล่องใส กล่องโชว์",
  "f6.t": "ห้องปฏิบัติการ QC", "f6.d": "ทดสอบการตก แรงดึง โลหะหนัก ฟทาเลต ตรวจสุดท้าย 100%",
  "sec.testi": "เสียงจากลูกค้า", "sec.testiSub": "รีวิวจากลูกค้าสามตลาดหลัก",
  "t1.q": "ความเร็วการทำตัวอย่างของ FiguRise ช่วยให้เราทันซีซันกล่องสุ่มเวียดนาม คุณภาพสม่ำเสมอ", "t1.n": "เหงียน วัน มิญ", "t1.r": "เวียดนาม · ผู้ค้าส่งออนไลน์",
  "t2.q": "พวกเขาให้คำแนะนำท้องถิ่นสำหรับตลาดซาอุดีฯ และจัดการบรรจุภัณฑ์และใบรับรองให้", "t2.n": "Ahmed Al-Rashid", "t2.r": "ซาอุดีอาระเบีย · ผู้ซื้อค้าปลีกเชน",
  "t3.q": "จากสอบถามถึงคอนเทนเนอร์แรกใน 60 วัน เอกสารศุลกากรลาตินอเมริกาครบถ้วน", "t3.n": "Carlos Mendes", "t3.r": "บราซิล · ผู้นำเข้าส่ง",
  "cta.title": "พร้อมนำฟิกเกอร์จีนสู่วงการโลกหรือยัง?", "cta.sub": "ส่งสอบถาม รับคำแนะนำเลือกสินค้าฟรี ใบเสนอราคาและแผนตัวอย่าง",
  "cta.btn1": "ส่งสอบถาม", "cta.btn2": "ถาม AI Brain",
  "footer.aboutText": "FiguRise เชี่ยวชาญฟิกเกอร์อนิเมะและของเล่นเทรนด์มา 12 ปี ช่วยผู้ซื้อทั่วโลกเข้าสู่ตลาดฟิกเกอร์อย่างคุ้มค่าและมั่นคง",
  "footer.linksTitle": "ลิงก์ด่วน", "footer.catsTitle": "หมวดหมู่", "footer.contactTitle": "ติดต่อ", "footer.regionsTitle": "พื้นที่บริการ",
  "footer.rights": "สงวนลิขสิทธิ์.", "footer.privacy": "นโยบายความเป็นส่วนตัว", "footer.terms": "เงื่อนไขบริการ",
  "p.title": "ศูนย์สินค้า", "p.sub": "ฟิกเกอร์ครบหมวด · OEM/ODM และขายส่ง · ราคาตามสอบถาม",
  "p.all": "ทุกหมวดหมู่", "p.search": "ค้นหาสินค้า (ชื่อ / คำค้น)…", "p.moq": "MOQ", "p.lead": "ระยะเวลาจัดส่ง", "p.scale": "สเกล/ขนาด",
  "p.inquire": "สอบถามเลย", "p.detail": "ดูรายละเอียด", "p.close": "ปิด", "p.features": "จุดเด่น", "p.why": "ทำไม FiguRise",
  "p.empty": "ไม่พบสินค้า ลองคำอื่นหรือส่งสอบถามความต้องการของคุณ",
  "p.priceHint": "ราคาตามสอบถาม (ปรับแต่งและส่วนลดปริมาณได้)", "p.qty": "ปริมาณโดยประมาณ", "p.oem": "รองรับ OEM/ODM",
  "a.title": "เกี่ยวกับเรา", "a.sub": "ผู้ผลิตฟิกเกอร์ 12 ปี จากเมืองหลวงของเล่นจีนสู่โลก",
  "a.storyTitle": "เรื่องราวของเรา",
  "a.storyP1": "ปี 2014 เราก่อตั้ง FiguRise ในซานโถว เมืองหลวงของเล่นจีน จากสตูดิโอช่างปั้น 8 คน สู่โรงงานครบวงจรสองฐาน ซานโถวและตงกวน พนักงาน 300+ คน",
  "a.storyP2": "เรายึดแนวคิด 'จากต้นแบบสู่การผลิต': IP ถูกกฎหมาย ดีไซน์ดั้งเดิม แม่พิมพ์ ฉีด พ่นสี พิมพ์ บรรจุ โลจิสติกส์ ครบในบ้าน",
  "a.storyP3": "วันนี้สินค้า FiguRise ไปถึง 40+ ประเทศ รับใช้ผู้ขายออนไลน์ ผู้ค้าส่ง ค้าปลีกเชน",
  "a.missionTitle": "พันธกิจ", "a.mission": "ช่วยแบรนด์ฟิกเกอร์จีนก้าวสู่โลกอย่างแม่นยำและมั่นคง",
  "a.baseTitle": "ฐานการผลิต", "a.facTitle": "โรงงานหลัก", "a.facSub": "ความสามารถในบ้านครอบคลุมทุกขั้นตอน",
  "a.qcTitle": "ระบบคุณภาพ", "a.qcSub": "สี่ด่านควบคุมคุณภาพ",
  "q1.t": "IQC - ขาเข้า", "q1.d": "สุ่มตรวจวัตถุดิบ สี บรรจุ 100%",
  "q2.t": "IPQC - ระหว่างผลิต", "q2.d": "บันทึกตรวจฉีด พ่นสี ประกอบ",
  "q3.t": "FQC - สำเร็จรูป", "q3.d": "ตรวจรูปลักษณ์ ฟังก์ชัน ประกอบ 100%",
  "q4.t": "OQC - ขาออก", "q4.d": "สุ่มตรวจบุคคลที่สาม + รายงานครบ",
  "a.timelineTitle": "เส้นทาง",
  "tl1.y": "2014", "tl1.t": "ก่อตั้งที่ซานโถว",
  "tl2.y": "2017", "tl2.t": "สายฉีด+พ่นสีครบ ผ่าน ISO9001",
  "tl3.y": "2020", "tl3.t": "ฐานตงกวน กำลังผลิตเกิน 1 ล้าน",
  "tl4.y": "2023", "tl4.t": "เปิดตัว AI Brain",
  "tl5.y": "2026", "tl5.t": "บริการ 40+ ประเทศ กำลังผลิต 2 ล้าน",
  "a.certTitle": "ใบรับรอง", "a.teamTitle": "ทีมบริการ", "a.teamSub": "เข้าใจสินค้า ตลาด และภาษา",
  "i.title": "ข้อมูลตลาด", "i.sub": "แนวโน้มตลาดฟิกเกอร์และคู่มือสั่งซื้อ เอเชียตะวันออกเฉียงใต้ ตะวันออกกลาง ลาตินอเมริกา",
  "i.region": "ตลาด", "i.updated": "อัปเดต", "i.readMore": "อ่านเพิ่ม", "i.download": "ดาวน์โหลดรายงาน",
  "i.note": "เนื้อหาจากข้อมูลสาธารณะและประสบการณ์จริงเพื่ออ้างอิง ควรตรวจสอบตลาดและกฎหมายท้องถิ่น",
  "c.title": "ติดต่อเรา", "c.sub": "ส่งสอบถามหรือติดต่อทีมขาย ตอบภายใน 12 ชั่วโมง (GMT+8)",
  "c.formTitle": "ส่งสอบถาม", "c.infoTitle": "ติดต่อตรง", "c.whyTitle": "ทำไมเลือกเรา",
  "c.name": "ชื่อ *", "c.company": "บริษัท", "c.email": "อีเมล *", "c.whatsapp": "WhatsApp / โทรศัพท์", "c.country": "ประเทศ/ภูมิภาค", "c.category": "หมวดสินค้า", "c.qty": "ปริมาณโดยประมาณ",
  "c.msg": "ความต้องการ (สไตล์ IP สเปก ตลาดเป้าหมาย…)",
  "c.phName": "ชื่อของคุณ", "c.phCompany": "บริษัท (ไม่บังคับ)", "c.phEmail": "name@company.com", "c.phWhat": "+86 138 0000 0000", "c.phCountry": "เช่น เวียดนาม / ซาอุดี / เม็กซิโก", "c.phQty": "เช่น สั่งแรก 3,000 ชิ้น",
  "c.phMsg": "อธิบายความต้องการสินค้า…", "c.submit": "ส่งสอบถาม",
  "c.successTitle": "ได้รับสอบถามแล้ว!", "c.successText": "ขอบคุณ! ผู้จัดการขายจะติดต่อภายใน 12 ชั่วโมง (GMT+8) ทางอีเมลหรือ WhatsApp",
  "c.sendAnother": "ส่งสอบถามอีกครั้ง", "c.errName": "กรุณากรอกชื่อ", "c.errEmail": "กรุณากรอกอีเมลที่ถูกต้อง", "c.errMsg": "กรุณาอธิบายความต้องการสั้นๆ",
  "c.regionsTitle": "ผู้จัดการขายประจำภูมิภาค", "c.officeLabel": "ดูแลตลาด", "c.hours": "เวลาทำการ: จ–ส 9:00–18:00 (GMT+8)",
  "c.why1": "ผลิต 12 ปี สองฐานครบวงจร", "c.why2": "ตัวอย่าง 7-15 วัน ผลิต 30-45 วัน",
  "c.why3": "ใบรับรองครบ + ตรวจ 100% + เอกสารศุลกากร", "c.why4": "ทีมภูมิภาค: SEA / ตะวันออกกลาง / ลาตินอเมริกา / ยุโรป", "c.why5": "คำแนะนำ AI ฟรี",
  "bot.title": "FiguBot AI Trade Brain", "bot.status": "ออนไลน์ · ตอบอัจฉริยะ",
  "bot.greeting": "สวัสดี! ฉันคือ FiguBot ที่ปรึกษา AI ส่งออกฟิกเกอร์ ฉันช่วยคุณ: <b>1. คัดเลือกสินค้า</b> · 2. คอนเทนต์ท้องถิ่น · 3. โฆษณาอัจฉริยะ · 4. คาดการณ์ซัพพลายเชน<br>กดการ์ดด้านล่างหรือพิมพ์คำถาม",
  "bot.placeholder": "พิมพ์คำถาม…", "bot.quick1": "คัดเลือกสินค้า", "bot.quick2": "คอนเทนต์ท้องถิ่น", "bot.quick3": "โฆษณาอัจฉริยะ", "bot.quick4": "ซัพพลายเชน",
  "bot.moduleTitle": "เลือกโมดูล", "bot.regionQ": "เลือกตลาดเป้าหมาย:", "bot.categoryQ": "เลือกหมวดหมู่:", "bot.budgetQ": "เลือกงบโฆษณารายเดือน:", "bot.destQ": "เลือกประเทศปลายทาง:",
  "bot.back": "กลับ", "bot.restart": "เริ่มใหม่", "bot.typing": "กำลังคิด…",
  "bot.default": "ฉันคือ AI Trade Brain มีบริการ 4 อย่าง: คัดเลือกสินค้า คอนเทนต์ท้องถิ่น โฆษณาอัจฉริยะ คาดการณ์ซัพพลายเชน กดการ์ดหรือถามตรงๆ (เช่น MOQ เท่าไหร่?)",
  "bot.apiError": "เชื่อมต่อโมเดลระยะไกลล้มเหลว เปลี่ยนเป็นเครื่องยนต์ความรู้ในตัวแล้ว", "bot.copied": "คัดลอกแล้ว", "bot.langs": "ฉันตอบเป็นภาษาจีนหรืออังกฤษ ภาษาอื่นพิมพ์เป็นภาษาอังกฤษ",
  "common.close": "ปิด", "common.cancel": "ยกเลิก", "common.next": "ถัดไป", "common.submit": "ส่ง", "common.copy": "คัดลอก", "common.days": "วัน"
});

/* ================= 印尼语 ================= */
window.__I18N_MERGE__("id", {
  "nav.home": "Beranda", "nav.products": "Produk", "nav.about": "Tentang Kami", "nav.insights": "Wawasan Pasar", "nav.contact": "Kontak", "nav.quote": "Minta Penawaran",
  "topbar.hint": "Pabrik Figure China · Melayani Pembeli Global",
  "hero.badge": "Made in China · Dikirim ke Seluruh Dunia",
  "hero.title": "Mitra Manufaktur <em>Figure</em> Premium untuk Pasar Global",
  "hero.sub": "Dari pemahatan prototipe dan injeksi plastik hingga produksi bersertifikat dan logistik global — pabrik OEM/ODM satu pintu untuk prize figure, articulated figure, blind box, dan patung koleksi. Dipercaya importir di 40+ negara.",
  "hero.cta1": "Lihat Katalog", "hero.cta2": "Minta Penawaran", "hero.scroll": "Gulir ke bawah",
  "hero.statYears": "Tahun Manufaktur", "hero.statPartners": "Mitra Global", "hero.statCapacity": "Kapasitas Tahunan (unit)", "hero.statOnTime": "Pengiriman Tepat Waktu",
  "marquee.label": "Pasar yang Kami Layani",
  "sec.strengths": "Keunggulan Utama", "sec.strengthsSub": "Mengapa pembeli global memilih FiguRise",
  "s1.t": "Kapabilitas OEM/ODM Penuh", "s1.d": "Manufaktur IP berlisensi dan pengembangan desain orisinal — dari seni 2D, pemodelan 3D, hingga produksi massal, semua terkendali.",
  "s2.t": "Sertifikasi Internasional", "s2.d": "ISO9001, BSCI, CE, EN71, ASTM F963 — kepatuhan penuh untuk akses pasar UE, AS, Timur Tengah, dan Asia Tenggara.",
  "s3.t": "Contoh Cepat 7-15 Hari", "s3.d": "Pemahat senior plus verifikasi cepat cetak 3D. Contoh berulang hingga disetujui, mengurangi biaya komunikasi.",
  "s4.t": "Rantai Pasok End-to-End", "s4.d": "Cetakan, injeksi, pengecatan, sablon, UV, dan kemasan in-house — mulus di setiap langkah.",
  "s5.t": "Solusi Logistik Global", "s5.d": "Laut LCL/FCL, udara, gudang luar negeri, dan jalur konsolidasi, dioptimalkan per tujuan.",
  "s6.t": "Layanan Konsultasi Khusus", "s6.d": "Sales manager 1-on-1 plus tim regional, respons 12 jam, dukungan penuh dari contoh hingga purna jual.",
  "sec.products": "Pusat Produk", "sec.productsSub": "Enam kategori · OEM/ODM & pembelian grosir",
  "products.viewAll": "Lihat Semua Produk", "products.more": "Pelajari Lebih Lanjut",
  "sec.regions": "Pasar Global", "sec.regionsSub": "Fokus tiga pasar pembeli utama dengan tim lokal",
  "r1.name": "Asia Tenggara", "r1.desc": "Permintaan blind box dan chibi melonjak, didorong social commerce.",
  "r2.name": "Timur Tengah", "r2.desc": "Koleksi bernilai tinggi, ekonomi hadiah dan budaya konvensi tumbuh.",
  "r3.name": "Amerika Latin", "r3.desc": "Penetrasi e-commerce tumbuh cepat, budaya anime dan IP lokal naik.",
  "r.tag": "Profil Pasar", "r.hot": "Kategori Panas", "r.advice": "Saran Pengadaan",
  "sec.process": "Cara Kami Bekerja", "sec.processSub": "Lima langkah memulai, transparan di setiap tahap",
  "proc1.t": "Diskusi & Inquiry", "proc1.d": "Kirim kebutuhan atau pilih produk. Sales manager merespons dalam 12 jam.",
  "proc2.t": "Konfirmasi Contoh", "proc2.d": "Contoh jadi 7-15 hari dengan revisi berulang. Biaya contoh dapat dikembalikan.",
  "proc3.t": "Produksi Pesanan", "proc3.d": "Produksi massal 30-45 hari setelah kontrak, laporan progres mingguan.",
  "proc4.t": "Inspeksi Kualitas", "proc4.d": "Jaminan ganda: inspeksi penuh + sampling pihak ketiga. Laporan sebelum pengiriman.",
  "proc5.t": "Pengiriman Global", "proc5.d": "Laut/udara/gudang luar negeri, dokumen bea cukai lengkap dan tracking.",
  "sec.factory": "Kekuatan Pabrik", "sec.factorySub": "Pabrik digital · 2 juta+ unit/tahun · 100% inspeksi",
  "f1.t": "Workshop Injeksi Presisi", "f1.d": "32 mesin injeksi, 60-500T, toleransi ±0,05mm.",
  "f2.t": "Pengecatan Bebas Debu", "f2.d": "Lini cat suhu konstan plus sablon otomatis, kontrol warna ketat.",
  "f3.t": "Prototipe Cepat 3D Print", "f3.d": "Verifikasi SLA/DLP, memangkas waktu iterasi 60%.",
  "f4.t": "Workshop Finishing Manual", "f4.d": "Pelukis senior untuk detail halus.",
  "f5.t": "Kemasan & Perakitan", "f5.d": "Desain dan produksi kotak kado, blister, dan kotak display.",
  "f6.t": "Laboratorium QC", "f6.d": "Uji jatuh, tarik, logam berat, ftalat. Inspeksi akhir 100%.",
  "sec.testi": "Kata Pembeli", "sec.testiSub": "Ulasan dari tiga pasar utama",
  "t1.q": "Kecepatan contoh FiguRise membuat kami unggul di musim puncak blind box Vietnam, kualitas selalu solid.", "t1.n": "Nguyen Van Minh", "t1.r": "Vietnam · Grosir e-commerce",
  "t2.q": "Mereka memberi saran lokalisasi profesional untuk pasar Saudi dan mengurus kemasan serta sertifikasi.", "t2.n": "Ahmed Al-Rashid", "t2.r": "Arab Saudi · Pembeli ritel berantai",
  "t3.q": "Dari inquiry ke kontainer pertama kurang dari 60 hari, dokumen bea cukai Amerika Latin lengkap.", "t3.n": "Carlos Mendes", "t3.r": "Brasil · Importir grosir",
  "cta.title": "Siap membawa figure China ke dunia?", "cta.sub": "Kirim inquiry untuk saran pemilihan produk gratis, penawaran, dan rencana contoh.",
  "cta.btn1": "Kirim Inquiry", "cta.btn2": "Tanya AI Brain",
  "footer.aboutText": "FiguRise mengkhususkan diri pada figure anime dan mainan tren selama 12 tahun, membantu pembeli global masuk pasar figure lebih hemat dan andal.",
  "footer.linksTitle": "Tautan Cepat", "footer.catsTitle": "Kategori", "footer.contactTitle": "Kontak", "footer.regionsTitle": "Wilayah Layanan",
  "footer.rights": "Hak cipta dilindungi.", "footer.privacy": "Kebijakan Privasi", "footer.terms": "Ketentuan Layanan",
  "p.title": "Pusat Produk", "p.sub": "Figure semua kategori · OEM/ODM & grosir · harga sesuai permintaan",
  "p.all": "Semua Kategori", "p.search": "Cari produk (nama / kata kunci)…", "p.moq": "MOQ", "p.lead": "Waktu Produksi", "p.scale": "Skala/Ukuran",
  "p.inquire": "Inquiry Sekarang", "p.detail": "Lihat Detail", "p.close": "Tutup", "p.features": "Keunggulan", "p.why": "Mengapa FiguRise",
  "p.empty": "Produk tidak ditemukan. Coba kata kunci lain atau kirim inquiry kebutuhan Anda.",
  "p.priceHint": "Harga sesuai permintaan (kustomisasi & diskon volume)", "p.qty": "Estimasi Kuantitas", "p.oem": "Dukungan OEM/ODM",
  "a.title": "Tentang Kami", "a.sub": "Produsen figure 12 tahun dari ibu kota mainan China ke dunia",
  "a.storyTitle": "Cerita Kami",
  "a.storyP1": "Tahun 2014 kami mendirikan FiguRise di Shantou, ibu kota mainan China. Dari studio 8 pemahat menjadi pabrik rantai penuh dengan dua basis di Shantou dan Dongguan, 300+ karyawan.",
  "a.storyP2": "Kami memegang filosofi 'dari prototipe ke produksi massal': lisensi IP, desain orisinal, cetakan, injeksi, cat, sablon, kemasan, logistik — semua in-house.",
  "a.storyP3": "Hari ini produk FiguRise hadir di 40+ negara, melayani penjual online, grosir, dan ritel berantai.",
  "a.missionTitle": "Misi Kami", "a.mission": "Membantu lebih banyak merek figure China go global secara lebih tepat dan andal.",
  "a.baseTitle": "Basis Produksi", "a.facTitle": "Fasilitas Inti", "a.facSub": "Kapasitas in-house mencakup setiap langkah produksi",
  "a.qcTitle": "Sistem Mutu", "a.qcSub": "Empat lapis kontrol kualitas",
  "q1.t": "IQC - Masuk", "q1.d": "Sampling 100% bahan baku, cat, kemasan.",
  "q2.t": "IPQC - Proses", "q2.d": "Catatan inspeksi injeksi, cat, perakitan.",
  "q3.t": "FQC - Akhir", "q3.d": "Cek 100% tampilan, fungsi, perakitan.",
  "q4.t": "OQC - Keluar", "q4.d": "Sampling pihak ketiga + laporan uji lengkap.",
  "a.timelineTitle": "Tonggak",
  "tl1.y": "2014", "tl1.t": "Didirikan di Shantou",
  "tl2.y": "2017", "tl2.t": "Lini injeksi + cat lengkap, ISO9001",
  "tl3.y": "2020", "tl3.t": "Basis Dongguan, kapasitas 1 juta+",
  "tl4.y": "2023", "tl4.t": "AI Brain untuk seleksi & pemasaran",
  "tl5.y": "2026", "tl5.t": "Melayani 40+ negara, kapasitas 2 juta",
  "a.certTitle": "Sertifikasi", "a.teamTitle": "Tim Layanan", "a.teamSub": "Paham produk, pasar, dan bahasa",
  "i.title": "Wawasan Pasar", "i.sub": "Tren pasar figure dan panduan pengadaan Asia Tenggara, Timur Tengah, Amerika Latin",
  "i.region": "Pasar", "i.updated": "Diperbarui", "i.readMore": "Baca Selengkapnya", "i.download": "Unduh Laporan",
  "i.note": "Konten dari data publik dan pengalaman lapangan sebagai referensi; verifikasi dengan pasar dan regulasi lokal.",
  "c.title": "Hubungi Kami", "c.sub": "Kirim inquiry atau hubungi tim penjualan — balas dalam 12 jam (GMT+8)",
  "c.formTitle": "Kirim Inquiry", "c.infoTitle": "Kontak Langsung", "c.whyTitle": "Mengapa Memilih Kami",
  "c.name": "Nama *", "c.company": "Perusahaan", "c.email": "Email *", "c.whatsapp": "WhatsApp / Telepon", "c.country": "Negara/Wilayah", "c.category": "Kategori Produk", "c.qty": "Estimasi Kuantitas",
  "c.msg": "Kebutuhan (gaya, IP, spesifikasi, pasar target…)",
  "c.phName": "Nama Anda", "c.phCompany": "Perusahaan (opsional)", "c.phEmail": "nama@perusahaan.com", "c.phWhat": "+86 138 0000 0000", "c.phCountry": "cth. Vietnam / Saudi / Meksiko", "c.phQty": "cth. Pesanan pertama 3.000 pcs",
  "c.phMsg": "Jelaskan kebutuhan produk…", "c.submit": "Kirim Inquiry",
  "c.successTitle": "Inquiry Diterima!", "c.successText": "Terima kasih! Sales manager akan menghubungi dalam 12 jam (GMT+8) via email atau WhatsApp.",
  "c.sendAnother": "Kirim Inquiry Lain", "c.errName": "Masukkan nama", "c.errEmail": "Masukkan email valid", "c.errMsg": "Jelaskan kebutuhan secara singkat",
  "c.regionsTitle": "Sales Manager Regional", "c.officeLabel": "Cakupan", "c.hours": "Jam kerja: Sen–Sab 9:00–18:00 (GMT+8)",
  "c.why1": "12 tahun manufaktur, dua basis", "c.why2": "Contoh 7-15 hari, produksi 30-45 hari",
  "c.why3": "Sertifikasi lengkap + 100% inspeksi + dokumen", "c.why4": "Tim regional: SEA / Timur Tengah / LatAm / Eropa", "c.why5": "Saran AI gratis",
  "bot.title": "FiguBot AI Trade Brain", "bot.status": "Online · Balasan Cerdas",
  "bot.greeting": "Halo! Saya FiguBot, penasihat AI ekspor figure Anda. Saya bisa membantu: <b>1. Wawasan Pemilihan Produk</b> · 2. Konten Lokalisasi · 3. Iklan Cerdas · 4. Perkiraan Rantai Pasok.<br>Ketuk kartu di bawah atau ketik pertanyaan.",
  "bot.placeholder": "Ketik pertanyaan…", "bot.quick1": "Pemilihan Produk", "bot.quick2": "Konten Lokalisasi", "bot.quick3": "Iklan Cerdas", "bot.quick4": "Rantai Pasok",
  "bot.moduleTitle": "Pilih modul", "bot.regionQ": "Pilih pasar target:", "bot.categoryQ": "Pilih kategori:", "bot.budgetQ": "Pilih anggaran iklan bulanan:", "bot.destQ": "Pilih negara tujuan:",
  "bot.back": "Kembali", "bot.restart": "Mulai Ulang", "bot.typing": "Berpikir…",
  "bot.default": "Saya AI Trade Brain. Saya menawarkan empat layanan: Wawasan Pemilihan Produk, Konten Lokalisasi, Iklan Cerdas, dan Perkiraan Rantai Pasok. Ketuk kartu atau tanya langsung (cth: Berapa MOQ-nya?).",
  "bot.apiError": "Koneksi model jarak jauh gagal. Beralih ke mesin pengetahuan bawaan.", "bot.copied": "Tersalin", "bot.langs": "Saya menjawab dalam bahasa Mandarin atau Inggris. Bahasa lain silakan ketik dalam bahasa Inggris.",
  "common.close": "Tutup", "common.cancel": "Batal", "common.next": "Berikutnya", "common.submit": "Kirim", "common.copy": "Salin", "common.days": "hari"
});
